#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : dma_passthrough.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jul 31 16:03:47 KST 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: dma_passthrough.sh [-help]
# usage: dma_passthrough.sh [-lib_map_path]
# usage: dma_passthrough.sh [-noclean_files]
# usage: dma_passthrough.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'dma_passthrough.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 xil_defaultlib lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_29 axi_sg_v4_1_15 axi_dma_v7_1_28 proc_sys_reset_v5_0_13 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_27 util_vector_logic_v2_0_2 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "dma_passthrough.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_zynq_ultra_ps_e_0_0/sim/dma_passthrough_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_28 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/70c4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/sim/dma_passthrough_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog/axis_passthrough_control_s_axi.v" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog/axis_passthrough_flow_control_loop_pipe.v" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog/axis_passthrough_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog/axis_passthrough_regslice_both.v" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog/axis_passthrough.v" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/sim/dma_passthrough_axis_passthrough_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_proc_sys_reset_0_0/sim/dma_passthrough_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/sim/bd_e2ba.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_0/sim/bd_e2ba_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_1/sim/bd_e2ba_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_2/sim/bd_e2ba_arsw_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_3/sim/bd_e2ba_rsw_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_4/sim/bd_e2ba_awsw_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_5/sim/bd_e2ba_wsw_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_6/sim/bd_e2ba_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_7/sim/bd_e2ba_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_8/sim/bd_e2ba_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_9/sim/bd_e2ba_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_10/sim/bd_e2ba_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_11/sim/bd_e2ba_sarn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_12/sim/bd_e2ba_srn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_13/sim/bd_e2ba_s01mmu_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_14/sim/bd_e2ba_s01tr_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_15/sim/bd_e2ba_s01sic_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_16/sim/bd_e2ba_s01a2s_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_17/sim/bd_e2ba_sawn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_18/sim/bd_e2ba_swn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_19/sim/bd_e2ba_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_20/sim/bd_e2ba_m00s2a_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_21/sim/bd_e2ba_m00arn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_22/sim/bd_e2ba_m00rn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_23/sim/bd_e2ba_m00awn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_24/sim/bd_e2ba_m00wn_0.sv" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_25/sim/bd_e2ba_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_26/sim/bd_e2ba_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/sim/dma_passthrough_smartconnect_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_reset_inverter_0_0/sim/dma_passthrough_reset_inverter_0_0.v" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_reset_const_high_0/sim/dma_passthrough_reset_const_high_0.v" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_reset_const_low_0/sim/dma_passthrough_reset_const_low_0.v" \
    "$ref_dir/../../../bd/dma_passthrough/sim/dma_passthrough.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_xbar_0/sim/dma_passthrough_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/92cc/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/drivers/axis_passthrough_v1_0/src" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_auto_ds_0/sim/dma_passthrough_auto_ds_0.v" \
    "$ref_dir/../../../bd/dma_passthrough/ip/dma_passthrough_auto_pc_0/sim/dma_passthrough_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.dma_passthrough xil_defaultlib.glbl -o dma_passthrough_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./dma_passthrough_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./dma_passthrough.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key dma_passthrough_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc dma_passthrough_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./dma_passthrough.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: dma_passthrough.sh [-help]\n\
Usage: dma_passthrough.sh [-lib_map_path]\n\
Usage: dma_passthrough.sh [-reset_run]\n\
Usage: dma_passthrough.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
