-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity split_channel_stream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_s_TVALID : IN STD_LOGIC;
    y0_s_TREADY : IN STD_LOGIC;
    y1_s_TREADY : IN STD_LOGIC;
    in_s_TDATA : IN STD_LOGIC_VECTOR (1023 downto 0);
    in_s_TREADY : OUT STD_LOGIC;
    y0_s_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    y0_s_TVALID : OUT STD_LOGIC;
    y1_s_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    y1_s_TVALID : OUT STD_LOGIC );
end;


architecture behav of split_channel_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "split_channel_stream_split_channel_stream,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.370875,HLS_SYN_LAT=1603,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1040,HLS_SYN_LUT=106,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_640 : STD_LOGIC_VECTOR (10 downto 0) := "11001000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv32_3FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111111111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln28_fu_84_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_y0_s_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y1_s_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_s_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal y0_s_TDATA_blk_n : STD_LOGIC;
    signal y1_s_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln40_fu_96_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal trunc_ln40_reg_126 : STD_LOGIC_VECTOR (511 downto 0);
    signal or_ln41_s_reg_131 : STD_LOGIC_VECTOR (511 downto 0);
    signal p_fu_52 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_2_fu_90_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_p_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal regslice_both_in_s_U_apdone_blk : STD_LOGIC;
    signal in_s_TDATA_int_regslice : STD_LOGIC_VECTOR (1023 downto 0);
    signal in_s_TVALID_int_regslice : STD_LOGIC;
    signal in_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_s_U_ack_in : STD_LOGIC;
    signal y0_s_TVALID_int_regslice : STD_LOGIC;
    signal y0_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y0_s_U_vld_out : STD_LOGIC;
    signal y1_s_TVALID_int_regslice : STD_LOGIC;
    signal y1_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y1_s_U_vld_out : STD_LOGIC;
    signal ap_condition_125 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component split_channel_stream_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component split_channel_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component split_channel_stream_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);

    regslice_both_in_s_U : component split_channel_stream_regslice_both
    generic map (
        DataWidth => 1024)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_s_TDATA,
        vld_in => in_s_TVALID,
        ack_in => regslice_both_in_s_U_ack_in,
        data_out => in_s_TDATA_int_regslice,
        vld_out => in_s_TVALID_int_regslice,
        ack_out => in_s_TREADY_int_regslice,
        apdone_blk => regslice_both_in_s_U_apdone_blk);

    regslice_both_y0_s_U : component split_channel_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => trunc_ln40_reg_126,
        vld_in => y0_s_TVALID_int_regslice,
        ack_in => y0_s_TREADY_int_regslice,
        data_out => y0_s_TDATA,
        vld_out => regslice_both_y0_s_U_vld_out,
        ack_out => y0_s_TREADY,
        apdone_blk => regslice_both_y0_s_U_apdone_blk);

    regslice_both_y1_s_U : component split_channel_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => or_ln41_s_reg_131,
        vld_in => y1_s_TVALID_int_regslice,
        ack_in => y1_s_TREADY_int_regslice,
        data_out => y1_s_TDATA,
        vld_out => regslice_both_y1_s_U_vld_out,
        ack_out => y1_s_TREADY,
        apdone_blk => regslice_both_y1_s_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    p_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_125)) then
                if ((icmp_ln28_fu_84_p2 = ap_const_lv1_0)) then 
                    p_fu_52 <= p_2_fu_90_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    p_fu_52 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or_ln41_s_reg_131 <= in_s_TDATA_int_regslice(1023 downto 512);
                trunc_ln40_reg_126 <= trunc_ln40_fu_96_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln28_fu_84_p2, regslice_both_y0_s_U_apdone_blk, regslice_both_y1_s_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, in_s_TVALID_int_regslice, y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1) or (y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0))) or ((icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (in_s_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln28_fu_84_p2, regslice_both_y0_s_U_apdone_blk, regslice_both_y1_s_U_apdone_blk, ap_block_state2_io, ap_block_state3_io, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, in_s_TVALID_int_regslice, y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1) or (y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io))) or ((icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (in_s_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln28_fu_84_p2, regslice_both_y0_s_U_apdone_blk, regslice_both_y1_s_U_apdone_blk, ap_block_state2_io, ap_block_state3_io, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, in_s_TVALID_int_regslice, y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1) or (y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io))) or ((icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (in_s_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln28_fu_84_p2, in_s_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (in_s_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_io_assign_proc : process(y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_both_y0_s_U_apdone_blk, regslice_both_y1_s_U_apdone_blk, y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_y1_s_U_apdone_blk = ap_const_logic_1) or (regslice_both_y0_s_U_apdone_blk = ap_const_logic_1) or (y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(y0_s_TREADY_int_regslice, y1_s_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((y1_s_TREADY_int_regslice = ap_const_logic_0) or (y0_s_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_125_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_125 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln28_fu_84_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln28_fu_84_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_exit_ready_pp0_iter1_reg, ap_block_pp0_stage0_subdone, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_p_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, p_fu_52, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_p_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_p_1 <= p_fu_52;
        end if; 
    end process;

    icmp_ln28_fu_84_p2 <= "1" when (ap_sig_allocacmp_p_1 = ap_const_lv11_640) else "0";

    in_s_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln28_fu_84_p2, ap_block_pp0_stage0, ap_start_int, in_s_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_s_TDATA_blk_n <= in_s_TVALID_int_regslice;
        else 
            in_s_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_s_TREADY <= regslice_both_in_s_U_ack_in;

    in_s_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln28_fu_84_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln28_fu_84_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_s_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_s_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_2_fu_90_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_p_1) + unsigned(ap_const_lv11_1));
    trunc_ln40_fu_96_p1 <= in_s_TDATA_int_regslice(512 - 1 downto 0);

    y0_s_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, y0_s_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            y0_s_TDATA_blk_n <= y0_s_TREADY_int_regslice;
        else 
            y0_s_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y0_s_TVALID <= regslice_both_y0_s_U_vld_out;

    y0_s_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            y0_s_TVALID_int_regslice <= ap_const_logic_1;
        else 
            y0_s_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    y1_s_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, y1_s_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            y1_s_TDATA_blk_n <= y1_s_TREADY_int_regslice;
        else 
            y1_s_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y1_s_TVALID <= regslice_both_y1_s_U_vld_out;

    y1_s_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            y1_s_TVALID_int_regslice <= ap_const_logic_1;
        else 
            y1_s_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
