-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity concat_channel_stream is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    y0_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    y0_s_TVALID : IN STD_LOGIC;
    y0_s_TREADY : OUT STD_LOGIC;
    y1_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    y1_s_TVALID : IN STD_LOGIC;
    y1_s_TREADY : OUT STD_LOGIC;
    y2_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    y2_s_TVALID : IN STD_LOGIC;
    y2_s_TREADY : OUT STD_LOGIC;
    y3_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    y3_s_TVALID : IN STD_LOGIC;
    y3_s_TREADY : OUT STD_LOGIC;
    out_s_TDATA : OUT STD_LOGIC_VECTOR (2047 downto 0);
    out_s_TVALID : OUT STD_LOGIC;
    out_s_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of concat_channel_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "concat_channel_stream_concat_channel_stream,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.057000,HLS_SYN_LAT=512037,HLS_SYN_TPT=none,HLS_SYN_MEM=150,HLS_SYN_DSP=0,HLS_SYN_FF=10061,HLS_SYN_LUT=12710,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal scale0 : STD_LOGIC_VECTOR (31 downto 0);
    signal scale1 : STD_LOGIC_VECTOR (31 downto 0);
    signal scale2 : STD_LOGIC_VECTOR (31 downto 0);
    signal scale3 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_scale : STD_LOGIC_VECTOR (31 downto 0);
    signal output_scale_read_reg_143 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal scale3_read_reg_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal scale2_read_reg_153 : STD_LOGIC_VECTOR (31 downto 0);
    signal scale1_read_reg_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal scale0_read_reg_163 : STD_LOGIC_VECTOR (31 downto 0);
    signal y0_buf_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal y0_buf_V_ce0 : STD_LOGIC;
    signal y0_buf_V_we0 : STD_LOGIC_VECTOR (3 downto 0);
    signal y0_buf_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal y1_buf_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal y1_buf_V_ce0 : STD_LOGIC;
    signal y1_buf_V_we0 : STD_LOGIC_VECTOR (3 downto 0);
    signal y1_buf_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal y2_buf_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal y2_buf_V_ce0 : STD_LOGIC;
    signal y2_buf_V_we0 : STD_LOGIC_VECTOR (3 downto 0);
    signal y2_buf_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer01_fu_110_ap_start : STD_LOGIC;
    signal grp_buffer01_fu_110_ap_done : STD_LOGIC;
    signal grp_buffer01_fu_110_ap_idle : STD_LOGIC;
    signal grp_buffer01_fu_110_ap_ready : STD_LOGIC;
    signal grp_buffer01_fu_110_y0_s_TREADY : STD_LOGIC;
    signal grp_buffer01_fu_110_y1_s_TREADY : STD_LOGIC;
    signal grp_buffer01_fu_110_y0_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_buffer01_fu_110_y0_buf_ce0 : STD_LOGIC;
    signal grp_buffer01_fu_110_y0_buf_we0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buffer01_fu_110_y0_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer01_fu_110_y1_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_buffer01_fu_110_y1_buf_ce0 : STD_LOGIC;
    signal grp_buffer01_fu_110_y1_buf_we0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buffer01_fu_110_y1_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer2_fu_120_ap_start : STD_LOGIC;
    signal grp_buffer2_fu_120_ap_done : STD_LOGIC;
    signal grp_buffer2_fu_120_ap_idle : STD_LOGIC;
    signal grp_buffer2_fu_120_ap_ready : STD_LOGIC;
    signal grp_buffer2_fu_120_y2_s_TREADY : STD_LOGIC;
    signal grp_buffer2_fu_120_y2_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_buffer2_fu_120_y2_buf_ce0 : STD_LOGIC;
    signal grp_buffer2_fu_120_y2_buf_we0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_buffer2_fu_120_y2_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_combine_fu_127_ap_start : STD_LOGIC;
    signal grp_combine_fu_127_ap_done : STD_LOGIC;
    signal grp_combine_fu_127_ap_idle : STD_LOGIC;
    signal grp_combine_fu_127_ap_ready : STD_LOGIC;
    signal grp_combine_fu_127_y3_s_TREADY : STD_LOGIC;
    signal grp_combine_fu_127_y0_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_combine_fu_127_y0_buf_ce0 : STD_LOGIC;
    signal grp_combine_fu_127_y1_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_combine_fu_127_y1_buf_ce0 : STD_LOGIC;
    signal grp_combine_fu_127_y2_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_combine_fu_127_y2_buf_ce0 : STD_LOGIC;
    signal grp_combine_fu_127_out_s_TDATA : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_combine_fu_127_out_s_TVALID : STD_LOGIC;
    signal grp_combine_fu_127_out_s_TREADY : STD_LOGIC;
    signal grp_buffer01_fu_110_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_buffer2_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal grp_combine_fu_127_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal regslice_both_out_s_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_y0_s_U_apdone_blk : STD_LOGIC;
    signal y0_s_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal y0_s_TVALID_int_regslice : STD_LOGIC;
    signal y0_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y0_s_U_ack_in : STD_LOGIC;
    signal regslice_both_y1_s_U_apdone_blk : STD_LOGIC;
    signal y1_s_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal y1_s_TVALID_int_regslice : STD_LOGIC;
    signal y1_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y1_s_U_ack_in : STD_LOGIC;
    signal regslice_both_y2_s_U_apdone_blk : STD_LOGIC;
    signal y2_s_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal y2_s_TVALID_int_regslice : STD_LOGIC;
    signal y2_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y2_s_U_ack_in : STD_LOGIC;
    signal regslice_both_y3_s_U_apdone_blk : STD_LOGIC;
    signal y3_s_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal y3_s_TVALID_int_regslice : STD_LOGIC;
    signal y3_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y3_s_U_ack_in : STD_LOGIC;
    signal out_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_s_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component concat_channel_stream_buffer01 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y0_s_TVALID : IN STD_LOGIC;
        y1_s_TVALID : IN STD_LOGIC;
        y0_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        y0_s_TREADY : OUT STD_LOGIC;
        y1_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        y1_s_TREADY : OUT STD_LOGIC;
        y0_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y0_buf_ce0 : OUT STD_LOGIC;
        y0_buf_we0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y0_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        y1_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y1_buf_ce0 : OUT STD_LOGIC;
        y1_buf_we0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y1_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component concat_channel_stream_buffer2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y2_s_TVALID : IN STD_LOGIC;
        y2_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        y2_s_TREADY : OUT STD_LOGIC;
        y2_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y2_buf_ce0 : OUT STD_LOGIC;
        y2_buf_we0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y2_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component concat_channel_stream_combine IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y3_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        y3_s_TVALID : IN STD_LOGIC;
        y3_s_TREADY : OUT STD_LOGIC;
        y0_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y0_buf_ce0 : OUT STD_LOGIC;
        y0_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        y1_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y1_buf_ce0 : OUT STD_LOGIC;
        y1_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        y2_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y2_buf_ce0 : OUT STD_LOGIC;
        y2_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale0 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale1 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale2 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale3 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_scale : IN STD_LOGIC_VECTOR (31 downto 0);
        out_s_TDATA : OUT STD_LOGIC_VECTOR (2047 downto 0);
        out_s_TVALID : OUT STD_LOGIC;
        out_s_TREADY : IN STD_LOGIC );
    end component;


    component concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC_VECTOR (3 downto 0);
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component concat_channel_stream_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        scale0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        scale1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        scale2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        scale3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_scale : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component concat_channel_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    y0_buf_V_U : component concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25600,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => y0_buf_V_address0,
        ce0 => y0_buf_V_ce0,
        we0 => y0_buf_V_we0,
        d0 => grp_buffer01_fu_110_y0_buf_d0,
        q0 => y0_buf_V_q0);

    y1_buf_V_U : component concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25600,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => y1_buf_V_address0,
        ce0 => y1_buf_V_ce0,
        we0 => y1_buf_V_we0,
        d0 => grp_buffer01_fu_110_y1_buf_d0,
        q0 => y1_buf_V_q0);

    y2_buf_V_U : component concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25600,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => y2_buf_V_address0,
        ce0 => y2_buf_V_ce0,
        we0 => y2_buf_V_we0,
        d0 => grp_buffer2_fu_120_y2_buf_d0,
        q0 => y2_buf_V_q0);

    grp_buffer01_fu_110 : component concat_channel_stream_buffer01
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_buffer01_fu_110_ap_start,
        ap_done => grp_buffer01_fu_110_ap_done,
        ap_idle => grp_buffer01_fu_110_ap_idle,
        ap_ready => grp_buffer01_fu_110_ap_ready,
        y0_s_TVALID => y0_s_TVALID_int_regslice,
        y1_s_TVALID => y1_s_TVALID_int_regslice,
        y0_s_TDATA => y0_s_TDATA_int_regslice,
        y0_s_TREADY => grp_buffer01_fu_110_y0_s_TREADY,
        y1_s_TDATA => y1_s_TDATA_int_regslice,
        y1_s_TREADY => grp_buffer01_fu_110_y1_s_TREADY,
        y0_buf_address0 => grp_buffer01_fu_110_y0_buf_address0,
        y0_buf_ce0 => grp_buffer01_fu_110_y0_buf_ce0,
        y0_buf_we0 => grp_buffer01_fu_110_y0_buf_we0,
        y0_buf_d0 => grp_buffer01_fu_110_y0_buf_d0,
        y1_buf_address0 => grp_buffer01_fu_110_y1_buf_address0,
        y1_buf_ce0 => grp_buffer01_fu_110_y1_buf_ce0,
        y1_buf_we0 => grp_buffer01_fu_110_y1_buf_we0,
        y1_buf_d0 => grp_buffer01_fu_110_y1_buf_d0);

    grp_buffer2_fu_120 : component concat_channel_stream_buffer2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_buffer2_fu_120_ap_start,
        ap_done => grp_buffer2_fu_120_ap_done,
        ap_idle => grp_buffer2_fu_120_ap_idle,
        ap_ready => grp_buffer2_fu_120_ap_ready,
        y2_s_TVALID => y2_s_TVALID_int_regslice,
        y2_s_TDATA => y2_s_TDATA_int_regslice,
        y2_s_TREADY => grp_buffer2_fu_120_y2_s_TREADY,
        y2_buf_address0 => grp_buffer2_fu_120_y2_buf_address0,
        y2_buf_ce0 => grp_buffer2_fu_120_y2_buf_ce0,
        y2_buf_we0 => grp_buffer2_fu_120_y2_buf_we0,
        y2_buf_d0 => grp_buffer2_fu_120_y2_buf_d0);

    grp_combine_fu_127 : component concat_channel_stream_combine
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_combine_fu_127_ap_start,
        ap_done => grp_combine_fu_127_ap_done,
        ap_idle => grp_combine_fu_127_ap_idle,
        ap_ready => grp_combine_fu_127_ap_ready,
        y3_s_TDATA => y3_s_TDATA_int_regslice,
        y3_s_TVALID => y3_s_TVALID_int_regslice,
        y3_s_TREADY => grp_combine_fu_127_y3_s_TREADY,
        y0_buf_address0 => grp_combine_fu_127_y0_buf_address0,
        y0_buf_ce0 => grp_combine_fu_127_y0_buf_ce0,
        y0_buf_q0 => y0_buf_V_q0,
        y1_buf_address0 => grp_combine_fu_127_y1_buf_address0,
        y1_buf_ce0 => grp_combine_fu_127_y1_buf_ce0,
        y1_buf_q0 => y1_buf_V_q0,
        y2_buf_address0 => grp_combine_fu_127_y2_buf_address0,
        y2_buf_ce0 => grp_combine_fu_127_y2_buf_ce0,
        y2_buf_q0 => y2_buf_V_q0,
        scale0 => scale0_read_reg_163,
        scale1 => scale1_read_reg_158,
        scale2 => scale2_read_reg_153,
        scale3 => scale3_read_reg_148,
        output_scale => output_scale_read_reg_143,
        out_s_TDATA => grp_combine_fu_127_out_s_TDATA,
        out_s_TVALID => grp_combine_fu_127_out_s_TVALID,
        out_s_TREADY => grp_combine_fu_127_out_s_TREADY);

    control_s_axi_U : component concat_channel_stream_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        scale0 => scale0,
        scale1 => scale1,
        scale2 => scale2,
        scale3 => scale3,
        output_scale => output_scale,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_y0_s_U : component concat_channel_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y0_s_TDATA,
        vld_in => y0_s_TVALID,
        ack_in => regslice_both_y0_s_U_ack_in,
        data_out => y0_s_TDATA_int_regslice,
        vld_out => y0_s_TVALID_int_regslice,
        ack_out => y0_s_TREADY_int_regslice,
        apdone_blk => regslice_both_y0_s_U_apdone_blk);

    regslice_both_y1_s_U : component concat_channel_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y1_s_TDATA,
        vld_in => y1_s_TVALID,
        ack_in => regslice_both_y1_s_U_ack_in,
        data_out => y1_s_TDATA_int_regslice,
        vld_out => y1_s_TVALID_int_regslice,
        ack_out => y1_s_TREADY_int_regslice,
        apdone_blk => regslice_both_y1_s_U_apdone_blk);

    regslice_both_y2_s_U : component concat_channel_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y2_s_TDATA,
        vld_in => y2_s_TVALID,
        ack_in => regslice_both_y2_s_U_ack_in,
        data_out => y2_s_TDATA_int_regslice,
        vld_out => y2_s_TVALID_int_regslice,
        ack_out => y2_s_TREADY_int_regslice,
        apdone_blk => regslice_both_y2_s_U_apdone_blk);

    regslice_both_y3_s_U : component concat_channel_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y3_s_TDATA,
        vld_in => y3_s_TVALID,
        ack_in => regslice_both_y3_s_U_ack_in,
        data_out => y3_s_TDATA_int_regslice,
        vld_out => y3_s_TVALID_int_regslice,
        ack_out => y3_s_TREADY_int_regslice,
        apdone_blk => regslice_both_y3_s_U_apdone_blk);

    regslice_both_out_s_U : component concat_channel_stream_regslice_both
    generic map (
        DataWidth => 2048)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_combine_fu_127_out_s_TDATA,
        vld_in => grp_combine_fu_127_out_s_TVALID,
        ack_in => out_s_TREADY_int_regslice,
        data_out => out_s_TDATA,
        vld_out => regslice_both_out_s_U_vld_out,
        ack_out => out_s_TREADY,
        apdone_blk => regslice_both_out_s_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_buffer01_fu_110_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_buffer01_fu_110_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_buffer01_fu_110_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_buffer01_fu_110_ap_ready = ap_const_logic_1)) then 
                    grp_buffer01_fu_110_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_buffer2_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_buffer2_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_buffer2_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_buffer2_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_buffer2_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_combine_fu_127_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_combine_fu_127_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_combine_fu_127_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_combine_fu_127_ap_ready = ap_const_logic_1)) then 
                    grp_combine_fu_127_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                output_scale_read_reg_143 <= output_scale;
                scale0_read_reg_163 <= scale0;
                scale1_read_reg_158 <= scale1;
                scale2_read_reg_153 <= scale2;
                scale3_read_reg_148 <= scale3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, grp_combine_fu_127_ap_done, ap_CS_fsm_state5, ap_block_state3_on_subcall_done, ap_CS_fsm_state6, regslice_both_out_s_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_combine_fu_127_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((regslice_both_out_s_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_combine_fu_127_ap_done)
    begin
        if ((grp_combine_fu_127_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(regslice_both_out_s_U_apdone_blk)
    begin
        if ((regslice_both_out_s_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_buffer01_fu_110_ap_done, grp_buffer2_fu_120_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_buffer01_fu_110_ap_done = ap_const_logic_0) or (grp_buffer2_fu_120_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_s_U_apdone_blk)
    begin
        if (((regslice_both_out_s_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_s_U_apdone_blk)
    begin
        if (((regslice_both_out_s_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_buffer01_fu_110_ap_start <= grp_buffer01_fu_110_ap_start_reg;
    grp_buffer2_fu_120_ap_start <= grp_buffer2_fu_120_ap_start_reg;
    grp_combine_fu_127_ap_start <= grp_combine_fu_127_ap_start_reg;
    grp_combine_fu_127_out_s_TREADY <= (out_s_TREADY_int_regslice and ap_CS_fsm_state5);
    out_s_TVALID <= regslice_both_out_s_U_vld_out;

    y0_buf_V_address0_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y0_buf_address0, grp_combine_fu_127_y0_buf_address0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y0_buf_V_address0 <= grp_combine_fu_127_y0_buf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y0_buf_V_address0 <= grp_buffer01_fu_110_y0_buf_address0;
        else 
            y0_buf_V_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    y0_buf_V_ce0_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y0_buf_ce0, grp_combine_fu_127_y0_buf_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y0_buf_V_ce0 <= grp_combine_fu_127_y0_buf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y0_buf_V_ce0 <= grp_buffer01_fu_110_y0_buf_ce0;
        else 
            y0_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y0_buf_V_we0_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y0_buf_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y0_buf_V_we0 <= grp_buffer01_fu_110_y0_buf_we0;
        else 
            y0_buf_V_we0 <= (0=>ap_const_logic_0, others=>'-');
        end if; 
    end process;

    y0_s_TREADY <= regslice_both_y0_s_U_ack_in;

    y0_s_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y0_s_TREADY)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y0_s_TREADY_int_regslice <= grp_buffer01_fu_110_y0_s_TREADY;
        else 
            y0_s_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    y1_buf_V_address0_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y1_buf_address0, grp_combine_fu_127_y1_buf_address0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y1_buf_V_address0 <= grp_combine_fu_127_y1_buf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y1_buf_V_address0 <= grp_buffer01_fu_110_y1_buf_address0;
        else 
            y1_buf_V_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    y1_buf_V_ce0_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y1_buf_ce0, grp_combine_fu_127_y1_buf_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y1_buf_V_ce0 <= grp_combine_fu_127_y1_buf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y1_buf_V_ce0 <= grp_buffer01_fu_110_y1_buf_ce0;
        else 
            y1_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y1_buf_V_we0_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y1_buf_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y1_buf_V_we0 <= grp_buffer01_fu_110_y1_buf_we0;
        else 
            y1_buf_V_we0 <= (0=>ap_const_logic_0, others=>'-');
        end if; 
    end process;

    y1_s_TREADY <= regslice_both_y1_s_U_ack_in;

    y1_s_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_buffer01_fu_110_y1_s_TREADY)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y1_s_TREADY_int_regslice <= grp_buffer01_fu_110_y1_s_TREADY;
        else 
            y1_s_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    y2_buf_V_address0_assign_proc : process(ap_CS_fsm_state3, grp_buffer2_fu_120_y2_buf_address0, grp_combine_fu_127_y2_buf_address0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y2_buf_V_address0 <= grp_combine_fu_127_y2_buf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y2_buf_V_address0 <= grp_buffer2_fu_120_y2_buf_address0;
        else 
            y2_buf_V_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    y2_buf_V_ce0_assign_proc : process(ap_CS_fsm_state3, grp_buffer2_fu_120_y2_buf_ce0, grp_combine_fu_127_y2_buf_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y2_buf_V_ce0 <= grp_combine_fu_127_y2_buf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y2_buf_V_ce0 <= grp_buffer2_fu_120_y2_buf_ce0;
        else 
            y2_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y2_buf_V_we0_assign_proc : process(ap_CS_fsm_state3, grp_buffer2_fu_120_y2_buf_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y2_buf_V_we0 <= grp_buffer2_fu_120_y2_buf_we0;
        else 
            y2_buf_V_we0 <= (0=>ap_const_logic_0, others=>'-');
        end if; 
    end process;

    y2_s_TREADY <= regslice_both_y2_s_U_ack_in;

    y2_s_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_buffer2_fu_120_y2_s_TREADY)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y2_s_TREADY_int_regslice <= grp_buffer2_fu_120_y2_s_TREADY;
        else 
            y2_s_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    y3_s_TREADY <= regslice_both_y3_s_U_ack_in;

    y3_s_TREADY_int_regslice_assign_proc : process(grp_combine_fu_127_y3_s_TREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y3_s_TREADY_int_regslice <= grp_combine_fu_127_y3_s_TREADY;
        else 
            y3_s_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
