// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="concat_channel_stream_concat_channel_stream,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.057000,HLS_SYN_LAT=512037,HLS_SYN_TPT=none,HLS_SYN_MEM=150,HLS_SYN_DSP=0,HLS_SYN_FF=10061,HLS_SYN_LUT=12710,HLS_VERSION=2022_2}" *)

module concat_channel_stream (
        ap_clk,
        ap_rst_n,
        y0_s_TDATA,
        y0_s_TVALID,
        y0_s_TREADY,
        y1_s_TDATA,
        y1_s_TVALID,
        y1_s_TREADY,
        y2_s_TDATA,
        y2_s_TVALID,
        y2_s_TREADY,
        y3_s_TDATA,
        y3_s_TVALID,
        y3_s_TREADY,
        out_s_TDATA,
        out_s_TVALID,
        out_s_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [511:0] y0_s_TDATA;
input   y0_s_TVALID;
output   y0_s_TREADY;
input  [511:0] y1_s_TDATA;
input   y1_s_TVALID;
output   y1_s_TREADY;
input  [511:0] y2_s_TDATA;
input   y2_s_TVALID;
output   y2_s_TREADY;
input  [511:0] y3_s_TDATA;
input   y3_s_TVALID;
output   y3_s_TREADY;
output  [2047:0] out_s_TDATA;
output   out_s_TVALID;
input   out_s_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] scale0;
wire   [31:0] scale1;
wire   [31:0] scale2;
wire   [31:0] scale3;
wire   [31:0] output_scale;
reg   [31:0] output_scale_read_reg_143;
wire    ap_CS_fsm_state3;
reg   [31:0] scale3_read_reg_148;
reg   [31:0] scale2_read_reg_153;
reg   [31:0] scale1_read_reg_158;
reg   [31:0] scale0_read_reg_163;
reg   [14:0] y0_buf_V_address0;
reg    y0_buf_V_ce0;
reg   [3:0] y0_buf_V_we0;
wire   [31:0] y0_buf_V_q0;
reg   [14:0] y1_buf_V_address0;
reg    y1_buf_V_ce0;
reg   [3:0] y1_buf_V_we0;
wire   [31:0] y1_buf_V_q0;
reg   [14:0] y2_buf_V_address0;
reg    y2_buf_V_ce0;
reg   [3:0] y2_buf_V_we0;
wire   [31:0] y2_buf_V_q0;
wire    grp_buffer01_fu_110_ap_start;
wire    grp_buffer01_fu_110_ap_done;
wire    grp_buffer01_fu_110_ap_idle;
wire    grp_buffer01_fu_110_ap_ready;
wire    grp_buffer01_fu_110_y0_s_TREADY;
wire    grp_buffer01_fu_110_y1_s_TREADY;
wire   [14:0] grp_buffer01_fu_110_y0_buf_address0;
wire    grp_buffer01_fu_110_y0_buf_ce0;
wire   [3:0] grp_buffer01_fu_110_y0_buf_we0;
wire   [31:0] grp_buffer01_fu_110_y0_buf_d0;
wire   [14:0] grp_buffer01_fu_110_y1_buf_address0;
wire    grp_buffer01_fu_110_y1_buf_ce0;
wire   [3:0] grp_buffer01_fu_110_y1_buf_we0;
wire   [31:0] grp_buffer01_fu_110_y1_buf_d0;
wire    grp_buffer2_fu_120_ap_start;
wire    grp_buffer2_fu_120_ap_done;
wire    grp_buffer2_fu_120_ap_idle;
wire    grp_buffer2_fu_120_ap_ready;
wire    grp_buffer2_fu_120_y2_s_TREADY;
wire   [14:0] grp_buffer2_fu_120_y2_buf_address0;
wire    grp_buffer2_fu_120_y2_buf_ce0;
wire   [3:0] grp_buffer2_fu_120_y2_buf_we0;
wire   [31:0] grp_buffer2_fu_120_y2_buf_d0;
wire    grp_combine_fu_127_ap_start;
wire    grp_combine_fu_127_ap_done;
wire    grp_combine_fu_127_ap_idle;
wire    grp_combine_fu_127_ap_ready;
wire    grp_combine_fu_127_y3_s_TREADY;
wire   [14:0] grp_combine_fu_127_y0_buf_address0;
wire    grp_combine_fu_127_y0_buf_ce0;
wire   [14:0] grp_combine_fu_127_y1_buf_address0;
wire    grp_combine_fu_127_y1_buf_ce0;
wire   [14:0] grp_combine_fu_127_y2_buf_address0;
wire    grp_combine_fu_127_y2_buf_ce0;
wire   [2047:0] grp_combine_fu_127_out_s_TDATA;
wire    grp_combine_fu_127_out_s_TVALID;
wire    grp_combine_fu_127_out_s_TREADY;
reg    grp_buffer01_fu_110_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_buffer2_fu_120_ap_start_reg;
reg    grp_combine_fu_127_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    ap_block_state3_on_subcall_done;
wire    ap_CS_fsm_state6;
wire    regslice_both_out_s_U_apdone_blk;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_y0_s_U_apdone_blk;
wire   [511:0] y0_s_TDATA_int_regslice;
wire    y0_s_TVALID_int_regslice;
reg    y0_s_TREADY_int_regslice;
wire    regslice_both_y0_s_U_ack_in;
wire    regslice_both_y1_s_U_apdone_blk;
wire   [511:0] y1_s_TDATA_int_regslice;
wire    y1_s_TVALID_int_regslice;
reg    y1_s_TREADY_int_regslice;
wire    regslice_both_y1_s_U_ack_in;
wire    regslice_both_y2_s_U_apdone_blk;
wire   [511:0] y2_s_TDATA_int_regslice;
wire    y2_s_TVALID_int_regslice;
reg    y2_s_TREADY_int_regslice;
wire    regslice_both_y2_s_U_ack_in;
wire    regslice_both_y3_s_U_apdone_blk;
wire   [511:0] y3_s_TDATA_int_regslice;
wire    y3_s_TVALID_int_regslice;
reg    y3_s_TREADY_int_regslice;
wire    regslice_both_y3_s_U_ack_in;
wire    out_s_TREADY_int_regslice;
wire    regslice_both_out_s_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_buffer01_fu_110_ap_start_reg = 1'b0;
#0 grp_buffer2_fu_120_ap_start_reg = 1'b0;
#0 grp_combine_fu_127_ap_start_reg = 1'b0;
end

concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25600 ),
    .AddressWidth( 15 ))
y0_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(y0_buf_V_address0),
    .ce0(y0_buf_V_ce0),
    .we0(y0_buf_V_we0),
    .d0(grp_buffer01_fu_110_y0_buf_d0),
    .q0(y0_buf_V_q0)
);

concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25600 ),
    .AddressWidth( 15 ))
y1_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(y1_buf_V_address0),
    .ce0(y1_buf_V_ce0),
    .we0(y1_buf_V_we0),
    .d0(grp_buffer01_fu_110_y1_buf_d0),
    .q0(y1_buf_V_q0)
);

concat_channel_stream_y0_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25600 ),
    .AddressWidth( 15 ))
y2_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(y2_buf_V_address0),
    .ce0(y2_buf_V_ce0),
    .we0(y2_buf_V_we0),
    .d0(grp_buffer2_fu_120_y2_buf_d0),
    .q0(y2_buf_V_q0)
);

concat_channel_stream_buffer01 grp_buffer01_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_buffer01_fu_110_ap_start),
    .ap_done(grp_buffer01_fu_110_ap_done),
    .ap_idle(grp_buffer01_fu_110_ap_idle),
    .ap_ready(grp_buffer01_fu_110_ap_ready),
    .y0_s_TVALID(y0_s_TVALID_int_regslice),
    .y1_s_TVALID(y1_s_TVALID_int_regslice),
    .y0_s_TDATA(y0_s_TDATA_int_regslice),
    .y0_s_TREADY(grp_buffer01_fu_110_y0_s_TREADY),
    .y1_s_TDATA(y1_s_TDATA_int_regslice),
    .y1_s_TREADY(grp_buffer01_fu_110_y1_s_TREADY),
    .y0_buf_address0(grp_buffer01_fu_110_y0_buf_address0),
    .y0_buf_ce0(grp_buffer01_fu_110_y0_buf_ce0),
    .y0_buf_we0(grp_buffer01_fu_110_y0_buf_we0),
    .y0_buf_d0(grp_buffer01_fu_110_y0_buf_d0),
    .y1_buf_address0(grp_buffer01_fu_110_y1_buf_address0),
    .y1_buf_ce0(grp_buffer01_fu_110_y1_buf_ce0),
    .y1_buf_we0(grp_buffer01_fu_110_y1_buf_we0),
    .y1_buf_d0(grp_buffer01_fu_110_y1_buf_d0)
);

concat_channel_stream_buffer2 grp_buffer2_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_buffer2_fu_120_ap_start),
    .ap_done(grp_buffer2_fu_120_ap_done),
    .ap_idle(grp_buffer2_fu_120_ap_idle),
    .ap_ready(grp_buffer2_fu_120_ap_ready),
    .y2_s_TVALID(y2_s_TVALID_int_regslice),
    .y2_s_TDATA(y2_s_TDATA_int_regslice),
    .y2_s_TREADY(grp_buffer2_fu_120_y2_s_TREADY),
    .y2_buf_address0(grp_buffer2_fu_120_y2_buf_address0),
    .y2_buf_ce0(grp_buffer2_fu_120_y2_buf_ce0),
    .y2_buf_we0(grp_buffer2_fu_120_y2_buf_we0),
    .y2_buf_d0(grp_buffer2_fu_120_y2_buf_d0)
);

concat_channel_stream_combine grp_combine_fu_127(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_combine_fu_127_ap_start),
    .ap_done(grp_combine_fu_127_ap_done),
    .ap_idle(grp_combine_fu_127_ap_idle),
    .ap_ready(grp_combine_fu_127_ap_ready),
    .y3_s_TDATA(y3_s_TDATA_int_regslice),
    .y3_s_TVALID(y3_s_TVALID_int_regslice),
    .y3_s_TREADY(grp_combine_fu_127_y3_s_TREADY),
    .y0_buf_address0(grp_combine_fu_127_y0_buf_address0),
    .y0_buf_ce0(grp_combine_fu_127_y0_buf_ce0),
    .y0_buf_q0(y0_buf_V_q0),
    .y1_buf_address0(grp_combine_fu_127_y1_buf_address0),
    .y1_buf_ce0(grp_combine_fu_127_y1_buf_ce0),
    .y1_buf_q0(y1_buf_V_q0),
    .y2_buf_address0(grp_combine_fu_127_y2_buf_address0),
    .y2_buf_ce0(grp_combine_fu_127_y2_buf_ce0),
    .y2_buf_q0(y2_buf_V_q0),
    .scale0(scale0_read_reg_163),
    .scale1(scale1_read_reg_158),
    .scale2(scale2_read_reg_153),
    .scale3(scale3_read_reg_148),
    .output_scale(output_scale_read_reg_143),
    .out_s_TDATA(grp_combine_fu_127_out_s_TDATA),
    .out_s_TVALID(grp_combine_fu_127_out_s_TVALID),
    .out_s_TREADY(grp_combine_fu_127_out_s_TREADY)
);

concat_channel_stream_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .scale0(scale0),
    .scale1(scale1),
    .scale2(scale2),
    .scale3(scale3),
    .output_scale(output_scale),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

concat_channel_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_y0_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(y0_s_TDATA),
    .vld_in(y0_s_TVALID),
    .ack_in(regslice_both_y0_s_U_ack_in),
    .data_out(y0_s_TDATA_int_regslice),
    .vld_out(y0_s_TVALID_int_regslice),
    .ack_out(y0_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_y0_s_U_apdone_blk)
);

concat_channel_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_y1_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(y1_s_TDATA),
    .vld_in(y1_s_TVALID),
    .ack_in(regslice_both_y1_s_U_ack_in),
    .data_out(y1_s_TDATA_int_regslice),
    .vld_out(y1_s_TVALID_int_regslice),
    .ack_out(y1_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_y1_s_U_apdone_blk)
);

concat_channel_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_y2_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(y2_s_TDATA),
    .vld_in(y2_s_TVALID),
    .ack_in(regslice_both_y2_s_U_ack_in),
    .data_out(y2_s_TDATA_int_regslice),
    .vld_out(y2_s_TVALID_int_regslice),
    .ack_out(y2_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_y2_s_U_apdone_blk)
);

concat_channel_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_y3_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(y3_s_TDATA),
    .vld_in(y3_s_TVALID),
    .ack_in(regslice_both_y3_s_U_ack_in),
    .data_out(y3_s_TDATA_int_regslice),
    .vld_out(y3_s_TVALID_int_regslice),
    .ack_out(y3_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_y3_s_U_apdone_blk)
);

concat_channel_stream_regslice_both #(
    .DataWidth( 2048 ))
regslice_both_out_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_combine_fu_127_out_s_TDATA),
    .vld_in(grp_combine_fu_127_out_s_TVALID),
    .ack_in(out_s_TREADY_int_regslice),
    .data_out(out_s_TDATA),
    .vld_out(regslice_both_out_s_U_vld_out),
    .ack_out(out_s_TREADY),
    .apdone_blk(regslice_both_out_s_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_buffer01_fu_110_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_buffer01_fu_110_ap_start_reg <= 1'b1;
        end else if ((grp_buffer01_fu_110_ap_ready == 1'b1)) begin
            grp_buffer01_fu_110_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_buffer2_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_buffer2_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_buffer2_fu_120_ap_ready == 1'b1)) begin
            grp_buffer2_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_combine_fu_127_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_combine_fu_127_ap_start_reg <= 1'b1;
        end else if ((grp_combine_fu_127_ap_ready == 1'b1)) begin
            grp_combine_fu_127_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        output_scale_read_reg_143 <= output_scale;
        scale0_read_reg_163 <= scale0;
        scale1_read_reg_158 <= scale1;
        scale2_read_reg_153 <= scale2;
        scale3_read_reg_148 <= scale3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_combine_fu_127_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_s_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_s_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_s_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y0_buf_V_address0 = grp_combine_fu_127_y0_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y0_buf_V_address0 = grp_buffer01_fu_110_y0_buf_address0;
    end else begin
        y0_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y0_buf_V_ce0 = grp_combine_fu_127_y0_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y0_buf_V_ce0 = grp_buffer01_fu_110_y0_buf_ce0;
    end else begin
        y0_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y0_buf_V_we0 = grp_buffer01_fu_110_y0_buf_we0;
    end else begin
        y0_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y0_s_TREADY_int_regslice = grp_buffer01_fu_110_y0_s_TREADY;
    end else begin
        y0_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y1_buf_V_address0 = grp_combine_fu_127_y1_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y1_buf_V_address0 = grp_buffer01_fu_110_y1_buf_address0;
    end else begin
        y1_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y1_buf_V_ce0 = grp_combine_fu_127_y1_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y1_buf_V_ce0 = grp_buffer01_fu_110_y1_buf_ce0;
    end else begin
        y1_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y1_buf_V_we0 = grp_buffer01_fu_110_y1_buf_we0;
    end else begin
        y1_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y1_s_TREADY_int_regslice = grp_buffer01_fu_110_y1_s_TREADY;
    end else begin
        y1_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y2_buf_V_address0 = grp_combine_fu_127_y2_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y2_buf_V_address0 = grp_buffer2_fu_120_y2_buf_address0;
    end else begin
        y2_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y2_buf_V_ce0 = grp_combine_fu_127_y2_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y2_buf_V_ce0 = grp_buffer2_fu_120_y2_buf_ce0;
    end else begin
        y2_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y2_buf_V_we0 = grp_buffer2_fu_120_y2_buf_we0;
    end else begin
        y2_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y2_s_TREADY_int_regslice = grp_buffer2_fu_120_y2_s_TREADY;
    end else begin
        y2_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y3_s_TREADY_int_regslice = grp_combine_fu_127_y3_s_TREADY;
    end else begin
        y3_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_combine_fu_127_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((regslice_both_out_s_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_buffer01_fu_110_ap_done == 1'b0) | (grp_buffer2_fu_120_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_buffer01_fu_110_ap_start = grp_buffer01_fu_110_ap_start_reg;

assign grp_buffer2_fu_120_ap_start = grp_buffer2_fu_120_ap_start_reg;

assign grp_combine_fu_127_ap_start = grp_combine_fu_127_ap_start_reg;

assign grp_combine_fu_127_out_s_TREADY = (out_s_TREADY_int_regslice & ap_CS_fsm_state5);

assign out_s_TVALID = regslice_both_out_s_U_vld_out;

assign y0_s_TREADY = regslice_both_y0_s_U_ack_in;

assign y1_s_TREADY = regslice_both_y1_s_U_ack_in;

assign y2_s_TREADY = regslice_both_y2_s_U_ack_in;

assign y3_s_TREADY = regslice_both_y3_s_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "concat_channel_stream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //concat_channel_stream

