// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="split_channel_stream_split_channel_stream,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.370875,HLS_SYN_LAT=1603,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1040,HLS_SYN_LUT=106,HLS_VERSION=2022_2}" *)

module split_channel_stream (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_s_TVALID,
        y0_s_TREADY,
        y1_s_TREADY,
        in_s_TDATA,
        in_s_TREADY,
        y0_s_TDATA,
        y0_s_TVALID,
        y1_s_TDATA,
        y1_s_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_s_TVALID;
input   y0_s_TREADY;
input   y1_s_TREADY;
input  [1023:0] in_s_TDATA;
output   in_s_TREADY;
output  [511:0] y0_s_TDATA;
output   y0_s_TVALID;
output  [511:0] y1_s_TDATA;
output   y1_s_TVALID;

reg ap_idle;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln28_fu_84_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_y0_s_U_apdone_blk;
wire    regslice_both_y1_s_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in_s_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    y0_s_TDATA_blk_n;
reg    y1_s_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [511:0] trunc_ln40_fu_96_p1;
reg   [511:0] trunc_ln40_reg_126;
reg   [511:0] or_ln41_s_reg_131;
reg   [10:0] p_fu_52;
wire   [10:0] p_2_fu_90_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_p_1;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    regslice_both_in_s_U_apdone_blk;
wire   [1023:0] in_s_TDATA_int_regslice;
wire    in_s_TVALID_int_regslice;
reg    in_s_TREADY_int_regslice;
wire    regslice_both_in_s_U_ack_in;
reg    y0_s_TVALID_int_regslice;
wire    y0_s_TREADY_int_regslice;
wire    regslice_both_y0_s_U_vld_out;
reg    y1_s_TVALID_int_regslice;
wire    y1_s_TREADY_int_regslice;
wire    regslice_both_y1_s_U_vld_out;
reg    ap_condition_125;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

split_channel_stream_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

split_channel_stream_regslice_both #(
    .DataWidth( 1024 ))
regslice_both_in_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_s_TDATA),
    .vld_in(in_s_TVALID),
    .ack_in(regslice_both_in_s_U_ack_in),
    .data_out(in_s_TDATA_int_regslice),
    .vld_out(in_s_TVALID_int_regslice),
    .ack_out(in_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_s_U_apdone_blk)
);

split_channel_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_y0_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(trunc_ln40_reg_126),
    .vld_in(y0_s_TVALID_int_regslice),
    .ack_in(y0_s_TREADY_int_regslice),
    .data_out(y0_s_TDATA),
    .vld_out(regslice_both_y0_s_U_vld_out),
    .ack_out(y0_s_TREADY),
    .apdone_blk(regslice_both_y0_s_U_apdone_blk)
);

split_channel_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_y1_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(or_ln41_s_reg_131),
    .vld_in(y1_s_TVALID_int_regslice),
    .ack_in(y1_s_TREADY_int_regslice),
    .data_out(y1_s_TDATA),
    .vld_out(regslice_both_y1_s_U_vld_out),
    .ack_out(y1_s_TREADY),
    .apdone_blk(regslice_both_y1_s_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_125)) begin
        if ((icmp_ln28_fu_84_p2 == 1'd0)) begin
            p_fu_52 <= p_2_fu_90_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_52 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_fu_84_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln41_s_reg_131 <= {{in_s_TDATA_int_regslice[1023:512]}};
        trunc_ln40_reg_126 <= trunc_ln40_fu_96_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln28_fu_84_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_p_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_p_1 = p_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln28_fu_84_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_s_TDATA_blk_n = in_s_TVALID_int_regslice;
    end else begin
        in_s_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_fu_84_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_s_TREADY_int_regslice = 1'b1;
    end else begin
        in_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        y0_s_TDATA_blk_n = y0_s_TREADY_int_regslice;
    end else begin
        y0_s_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y0_s_TVALID_int_regslice = 1'b1;
    end else begin
        y0_s_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        y1_s_TDATA_blk_n = y1_s_TREADY_int_regslice;
    end else begin
        y1_s_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y1_s_TVALID_int_regslice = 1'b1;
    end else begin
        y1_s_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1) | (y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0))) | ((icmp_ln28_fu_84_p2 == 1'd0) & (ap_start_int == 1'b1) & (in_s_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3_io))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1) | (y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io))) | ((icmp_ln28_fu_84_p2 == 1'd0) & (ap_start_int == 1'b1) & (in_s_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3_io))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1) | (y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io))) | ((icmp_ln28_fu_84_p2 == 1'd0) & (ap_start_int == 1'b1) & (in_s_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln28_fu_84_p2 == 1'd0) & (in_s_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_y1_s_U_apdone_blk == 1'b1) | (regslice_both_y0_s_U_apdone_blk == 1'b1) | (y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((y1_s_TREADY_int_regslice == 1'b0) | (y0_s_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_125 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln28_fu_84_p2 = ((ap_sig_allocacmp_p_1 == 11'd1600) ? 1'b1 : 1'b0);

assign in_s_TREADY = regslice_both_in_s_U_ack_in;

assign p_2_fu_90_p2 = (ap_sig_allocacmp_p_1 + 11'd1);

assign trunc_ln40_fu_96_p1 = in_s_TDATA_int_regslice[511:0];

assign y0_s_TVALID = regslice_both_y0_s_U_vld_out;

assign y1_s_TVALID = regslice_both_y1_s_U_vld_out;


reg find_kernel_block = 0;
// synthesis translate_off
`include "split_channel_stream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //split_channel_stream

