# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.runs/synth_1/dma_passthrough_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param chipscope.maxJobs 1
set_param power.BramSDPPropagationFix 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.cache/wt [current_project]
set_property parent.project_path /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property board_connections {som240_1_connector xilinx.com:kv260_carrier:som240_1_connector:1.3} [current_project]
set_property ip_repo_paths /home/sogang/ppe_fpga_ho/axis/passthrough/axis_passthrough_hls/solution1/impl/ip [current_project]
update_ip_catalog
set_property ip_output_repo /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/hdl/dma_passthrough_wrapper.v
add_files /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.srcs/sources_1/bd/dma_passthrough/dma_passthrough.bd
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_zynq_ultra_ps_e_0_0/dma_passthrough_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_zynq_ultra_ps_e_0_0/dma_passthrough_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/constraints/axis_passthrough_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_proc_sys_reset_0_0/dma_passthrough_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_proc_sys_reset_0_0/dma_passthrough_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_proc_sys_reset_0_0/dma_passthrough_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_1/bd_e2ba_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_1/bd_e2ba_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_2/bd_e2ba_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_3/bd_e2ba_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_4/bd_e2ba_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_5/bd_e2ba_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_6/bd_e2ba_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_10/bd_e2ba_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_11/bd_e2ba_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_12/bd_e2ba_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_16/bd_e2ba_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_17/bd_e2ba_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_18/bd_e2ba_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_19/bd_e2ba_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_20/bd_e2ba_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_21/bd_e2ba_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_22/bd_e2ba_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_23/bd_e2ba_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_24/bd_e2ba_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/bd_0/ip/ip_25/bd_e2ba_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_xbar_0/dma_passthrough_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_auto_ds_0/dma_passthrough_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_auto_ds_0/dma_passthrough_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_auto_ds_0/dma_passthrough_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_auto_pc_0/dma_passthrough_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/dma_passthrough_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.srcs/utils_1/imports/synth_1/dma_passthrough_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top dma_passthrough_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dma_passthrough_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dma_passthrough_wrapper_utilization_synth.rpt -pb dma_passthrough_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
