# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dma_passthrough/dma_passthrough.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough || ORIG_REF_NAME==dma_passthrough} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_zynq_ultra_ps_e_0_0/dma_passthrough_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==dma_passthrough_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_axi_dma_0_0 || ORIG_REF_NAME==dma_passthrough_axi_dma_0_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_axis_passthrough_0_0/dma_passthrough_axis_passthrough_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_axis_passthrough_0_0 || ORIG_REF_NAME==dma_passthrough_axis_passthrough_0_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_proc_sys_reset_0_0/dma_passthrough_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_proc_sys_reset_0_0 || ORIG_REF_NAME==dma_passthrough_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_smartconnect_1_0/dma_passthrough_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_smartconnect_1_0 || ORIG_REF_NAME==dma_passthrough_smartconnect_1_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_reset_inverter_0_0/dma_passthrough_reset_inverter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_reset_inverter_0_0 || ORIG_REF_NAME==dma_passthrough_reset_inverter_0_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_reset_const_high_0/dma_passthrough_reset_const_high_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_reset_const_high_0 || ORIG_REF_NAME==dma_passthrough_reset_const_high_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_reset_const_low_0/dma_passthrough_reset_const_low_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_reset_const_low_0 || ORIG_REF_NAME==dma_passthrough_reset_const_low_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_xbar_0/dma_passthrough_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_xbar_0 || ORIG_REF_NAME==dma_passthrough_xbar_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_auto_ds_0/dma_passthrough_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_auto_ds_0 || ORIG_REF_NAME==dma_passthrough_auto_ds_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_auto_pc_0/dma_passthrough_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_auto_pc_0 || ORIG_REF_NAME==dma_passthrough_auto_pc_0} -quiet] -quiet

# IP: bd/dma_passthrough/ip/dma_passthrough_axi_interconnect_0_0/dma_passthrough_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_passthrough_axi_interconnect_0_0 || ORIG_REF_NAME==dma_passthrough_axi_interconnect_0_0} -quiet] -quiet

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/dma_passthrough_ooc.xdc
