
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxis_passthrough.h"

/*
* The configuration table for devices
*/

XAxis_passthrough_Config XAxis_passthrough_ConfigTable[XPAR_XAXIS_PASSTHROUGH_NUM_INSTANCES] =
{
	{
		XPAR_AXIS_PASSTHROUGH_0_DEVICE_ID,
		XPAR_AXIS_PASSTHROUGH_0_S_AXI_CONTROL_BASEADDR
	}
};


