# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.srcs/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0.xci
# IP: The module: 'dma_passthrough_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_passthrough_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_passthrough_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_passthrough_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.srcs/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0.xci
# IP: The module: 'dma_passthrough_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_passthrough_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_passthrough_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/ppe_fpga_ho/ppe_dma_passthrough/ppe_dma_passthrough.gen/sources_1/bd/dma_passthrough/ip/dma_passthrough_axi_dma_0_0/dma_passthrough_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_passthrough_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
