// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="residual_add_stream_residual_add_stream,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.057000,HLS_SYN_LAT=102435,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4755,HLS_SYN_LUT=5907,HLS_VERSION=2022_2}" *)

module residual_add_stream (
        ap_clk,
        ap_rst_n,
        x_s_TDATA,
        x_s_TVALID,
        x_s_TREADY,
        fx_s_TDATA,
        fx_s_TVALID,
        fx_s_TREADY,
        out_s_TDATA,
        out_s_TVALID,
        out_s_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [511:0] x_s_TDATA;
input   x_s_TVALID;
output   x_s_TREADY;
input  [511:0] fx_s_TDATA;
input   fx_s_TVALID;
output   fx_s_TREADY;
output  [511:0] out_s_TDATA;
output   out_s_TVALID;
input   out_s_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] x_scale;
wire   [31:0] fx_scale;
wire   [31:0] output_scale;
reg   [31:0] output_scale_read_reg_88;
reg   [31:0] fx_scale_read_reg_93;
reg   [31:0] x_scale_read_reg_98;
wire   [31:0] grp_fu_83_p2;
reg   [31:0] inv_out_reg_103;
wire    ap_CS_fsm_state10;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_done;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_idle;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_ready;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TREADY;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_x_s_TREADY;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_fx_s_TREADY;
wire   [511:0] grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TDATA;
wire    grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TVALID;
reg    grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state13;
wire    regslice_both_out_s_U_apdone_blk;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    regslice_both_x_s_U_apdone_blk;
wire   [511:0] x_s_TDATA_int_regslice;
wire    x_s_TVALID_int_regslice;
reg    x_s_TREADY_int_regslice;
wire    regslice_both_x_s_U_ack_in;
wire    regslice_both_fx_s_U_apdone_blk;
wire   [511:0] fx_s_TDATA_int_regslice;
wire    fx_s_TVALID_int_regslice;
reg    fx_s_TREADY_int_regslice;
wire    regslice_both_fx_s_U_ack_in;
wire    out_s_TREADY_int_regslice;
wire    regslice_both_out_s_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start_reg = 1'b0;
end

residual_add_stream_residual_add_stream_Pipeline_MAIN grp_residual_add_stream_Pipeline_MAIN_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start),
    .ap_done(grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_done),
    .ap_idle(grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_idle),
    .ap_ready(grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_ready),
    .x_s_TVALID(x_s_TVALID_int_regslice),
    .fx_s_TVALID(fx_s_TVALID_int_regslice),
    .out_s_TREADY(grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TREADY),
    .x_scale(x_scale_read_reg_98),
    .fx_scale(fx_scale_read_reg_93),
    .inv_out(inv_out_reg_103),
    .x_s_TDATA(x_s_TDATA_int_regslice),
    .x_s_TREADY(grp_residual_add_stream_Pipeline_MAIN_fu_70_x_s_TREADY),
    .fx_s_TDATA(fx_s_TDATA_int_regslice),
    .fx_s_TREADY(grp_residual_add_stream_Pipeline_MAIN_fu_70_fx_s_TREADY),
    .out_s_TDATA(grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TDATA),
    .out_s_TVALID(grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TVALID)
);

residual_add_stream_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_scale(x_scale),
    .fx_scale(fx_scale),
    .output_scale(output_scale),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

residual_add_stream_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U91(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(32'd1065353216),
    .din1(output_scale_read_reg_88),
    .ce(1'b1),
    .dout(grp_fu_83_p2)
);

residual_add_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_x_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_s_TDATA),
    .vld_in(x_s_TVALID),
    .ack_in(regslice_both_x_s_U_ack_in),
    .data_out(x_s_TDATA_int_regslice),
    .vld_out(x_s_TVALID_int_regslice),
    .ack_out(x_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_s_U_apdone_blk)
);

residual_add_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_fx_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(fx_s_TDATA),
    .vld_in(fx_s_TVALID),
    .ack_in(regslice_both_fx_s_U_ack_in),
    .data_out(fx_s_TDATA_int_regslice),
    .vld_out(fx_s_TVALID_int_regslice),
    .ack_out(fx_s_TREADY_int_regslice),
    .apdone_blk(regslice_both_fx_s_U_apdone_blk)
);

residual_add_stream_regslice_both #(
    .DataWidth( 512 ))
regslice_both_out_s_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TDATA),
    .vld_in(grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TVALID),
    .ack_in(out_s_TREADY_int_regslice),
    .data_out(out_s_TDATA),
    .vld_out(regslice_both_out_s_U_vld_out),
    .ack_out(out_s_TREADY),
    .apdone_blk(regslice_both_out_s_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_ready == 1'b1)) begin
            grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        fx_scale_read_reg_93 <= fx_scale;
        output_scale_read_reg_88 <= output_scale;
        x_scale_read_reg_98 <= x_scale;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        inv_out_reg_103 <= grp_fu_83_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_s_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (regslice_both_out_s_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (regslice_both_out_s_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        fx_s_TREADY_int_regslice = grp_residual_add_stream_Pipeline_MAIN_fu_70_fx_s_TREADY;
    end else begin
        fx_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        x_s_TREADY_int_regslice = grp_residual_add_stream_Pipeline_MAIN_fu_70_x_s_TREADY;
    end else begin
        x_s_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (regslice_both_out_s_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign fx_s_TREADY = regslice_both_fx_s_U_ack_in;

assign grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start = grp_residual_add_stream_Pipeline_MAIN_fu_70_ap_start_reg;

assign grp_residual_add_stream_Pipeline_MAIN_fu_70_out_s_TREADY = (out_s_TREADY_int_regslice & ap_CS_fsm_state12);

assign out_s_TVALID = regslice_both_out_s_U_vld_out;

assign x_s_TREADY = regslice_both_x_s_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "residual_add_stream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //residual_add_stream

