// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module concat_channel_stream_combine (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y3_s_TDATA,
        y3_s_TVALID,
        y3_s_TREADY,
        y0_buf_address0,
        y0_buf_ce0,
        y0_buf_q0,
        y1_buf_address0,
        y1_buf_ce0,
        y1_buf_q0,
        y2_buf_address0,
        y2_buf_ce0,
        y2_buf_q0,
        scale0,
        scale1,
        scale2,
        scale3,
        output_scale,
        out_s_TDATA,
        out_s_TVALID,
        out_s_TREADY
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] y3_s_TDATA;
input   y3_s_TVALID;
output   y3_s_TREADY;
output  [14:0] y0_buf_address0;
output   y0_buf_ce0;
input  [31:0] y0_buf_q0;
output  [14:0] y1_buf_address0;
output   y1_buf_ce0;
input  [31:0] y1_buf_q0;
output  [14:0] y2_buf_address0;
output   y2_buf_ce0;
input  [31:0] y2_buf_q0;
input  [31:0] scale0;
input  [31:0] scale1;
input  [31:0] scale2;
input  [31:0] scale3;
input  [31:0] output_scale;
output  [2047:0] out_s_TDATA;
output   out_s_TVALID;
input   out_s_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y3_s_TREADY;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state9;
wire   [31:0] grp_fu_91_p2;
reg   [31:0] inv_out_reg_122;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_idle;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_ready;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TREADY;
wire   [14:0] grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_address0;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_ce0;
wire   [14:0] grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_address0;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_ce0;
wire   [14:0] grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_address0;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_ce0;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY;
wire   [2047:0] grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TDATA;
wire    grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TVALID;
reg    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg;
reg   [10:0] ap_NS_fsm;
wire    ap_NS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg = 1'b0;
end

concat_channel_stream_combine_Pipeline_COMBINE_MAIN grp_combine_Pipeline_COMBINE_MAIN_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start),
    .ap_done(grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done),
    .ap_idle(grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_idle),
    .ap_ready(grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_ready),
    .y3_s_TVALID(y3_s_TVALID),
    .out_s_TREADY(grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TREADY),
    .y0_buf_address0(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_address0),
    .y0_buf_ce0(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_ce0),
    .y0_buf_q0(y0_buf_q0),
    .y1_buf_address0(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_address0),
    .y1_buf_ce0(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_ce0),
    .y1_buf_q0(y1_buf_q0),
    .y2_buf_address0(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_address0),
    .y2_buf_ce0(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_ce0),
    .y2_buf_q0(y2_buf_q0),
    .scale0(scale0),
    .scale3(scale3),
    .scale1(scale1),
    .scale2(scale2),
    .inv_out(inv_out_reg_122),
    .y3_s_TDATA(y3_s_TDATA),
    .y3_s_TREADY(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY),
    .out_s_TDATA(grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TDATA),
    .out_s_TVALID(grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TVALID)
);

concat_channel_stream_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U296(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(output_scale),
    .ce(1'b1),
    .dout(grp_fu_91_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) & (1'b1 == ap_NS_fsm_state10))) begin
            grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_ready == 1'b1)) begin
            grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        inv_out_reg_122 <= grp_fu_91_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        y3_s_TREADY = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY;
    end else begin
        y3_s_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state10 = ap_NS_fsm[32'd9];

assign grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start = grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg;

assign grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TREADY = (out_s_TREADY & ap_CS_fsm_state11);

assign out_s_TDATA = grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TDATA;

assign out_s_TVALID = grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TVALID;

assign y0_buf_address0 = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_address0;

assign y0_buf_ce0 = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_ce0;

assign y1_buf_address0 = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_address0;

assign y1_buf_ce0 = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_ce0;

assign y2_buf_address0 = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_address0;

assign y2_buf_ce0 = grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_ce0;

endmodule //concat_channel_stream_combine
