// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module concat_channel_stream_buffer2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y2_s_TVALID,
        y2_s_TDATA,
        y2_s_TREADY,
        y2_buf_address0,
        y2_buf_ce0,
        y2_buf_we0,
        y2_buf_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   y2_s_TVALID;
input  [511:0] y2_s_TDATA;
output   y2_s_TREADY;
output  [14:0] y2_buf_address0;
output   y2_buf_ce0;
output  [3:0] y2_buf_we0;
output  [31:0] y2_buf_d0;

reg ap_idle;
reg y2_s_TREADY;
reg y2_buf_ce0;
reg[3:0] y2_buf_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln67_fu_890_p2;
wire   [0:0] icmp_ln72_fu_914_p2;
reg    ap_predicate_op280_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    y2_s_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [5:0] c_fu_902_p1;
reg   [5:0] c_reg_5388;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_11_fu_906_p3;
reg   [0:0] tmp_11_reg_5397;
wire   [63:0] zext_ln80_4_fu_4097_p1;
reg   [16:0] t_fu_330;
wire   [16:0] t_4_fu_896_p2;
wire    ap_loop_init;
reg   [16:0] ap_sig_allocacmp_t_3;
reg   [31:0] w_fu_334;
wire   [31:0] w_5_fu_4442_p3;
reg   [31:0] h_fu_338;
wire   [31:0] h_3_fu_4450_p3;
reg   [7:0] p2_V_62_fu_342;
wire   [7:0] select_ln76_127_fu_2954_p3;
reg   [7:0] p2_V_61_fu_346;
wire   [7:0] select_ln76_126_fu_2946_p3;
reg   [7:0] p2_V_60_fu_350;
wire   [7:0] select_ln76_125_fu_2938_p3;
reg   [7:0] p2_V_59_fu_354;
wire   [7:0] select_ln76_124_fu_2930_p3;
reg   [7:0] p2_V_58_fu_358;
wire   [7:0] select_ln76_123_fu_2922_p3;
reg   [7:0] p2_V_57_fu_362;
wire   [7:0] select_ln76_122_fu_2914_p3;
reg   [7:0] p2_V_56_fu_366;
wire   [7:0] select_ln76_121_fu_2906_p3;
reg   [7:0] p2_V_55_fu_370;
wire   [7:0] select_ln76_120_fu_2898_p3;
reg   [7:0] p2_V_54_fu_374;
wire   [7:0] select_ln76_119_fu_2890_p3;
reg   [7:0] p2_V_53_fu_378;
wire   [7:0] select_ln76_118_fu_2882_p3;
reg   [7:0] p2_V_52_fu_382;
wire   [7:0] select_ln76_117_fu_2874_p3;
reg   [7:0] p2_V_51_fu_386;
wire   [7:0] select_ln76_116_fu_2866_p3;
reg   [7:0] p2_V_50_fu_390;
wire   [7:0] select_ln76_115_fu_2858_p3;
reg   [7:0] p2_V_49_fu_394;
wire   [7:0] select_ln76_114_fu_2850_p3;
reg   [7:0] p2_V_48_fu_398;
wire   [7:0] select_ln76_113_fu_2842_p3;
reg   [7:0] p2_V_47_fu_402;
wire   [7:0] select_ln76_112_fu_2834_p3;
reg   [7:0] p2_V_46_fu_406;
wire   [7:0] select_ln76_111_fu_2826_p3;
reg   [7:0] p2_V_45_fu_410;
wire   [7:0] select_ln76_110_fu_2818_p3;
reg   [7:0] p2_V_44_fu_414;
wire   [7:0] select_ln76_109_fu_2810_p3;
reg   [7:0] p2_V_43_fu_418;
wire   [7:0] select_ln76_108_fu_2802_p3;
reg   [7:0] p2_V_42_fu_422;
wire   [7:0] select_ln76_107_fu_2794_p3;
reg   [7:0] p2_V_41_fu_426;
wire   [7:0] select_ln76_106_fu_2786_p3;
reg   [7:0] p2_V_40_fu_430;
wire   [7:0] select_ln76_105_fu_2778_p3;
reg   [7:0] p2_V_39_fu_434;
wire   [7:0] select_ln76_104_fu_2770_p3;
reg   [7:0] p2_V_38_fu_438;
wire   [7:0] select_ln76_103_fu_2762_p3;
reg   [7:0] p2_V_37_fu_442;
wire   [7:0] select_ln76_102_fu_2754_p3;
reg   [7:0] p2_V_36_fu_446;
wire   [7:0] select_ln76_101_fu_2746_p3;
reg   [7:0] p2_V_35_fu_450;
wire   [7:0] select_ln76_100_fu_2738_p3;
reg   [7:0] p2_V_34_fu_454;
wire   [7:0] select_ln76_99_fu_2730_p3;
reg   [7:0] p2_V_33_fu_458;
wire   [7:0] select_ln76_98_fu_2722_p3;
reg   [7:0] p2_V_32_fu_462;
wire   [7:0] select_ln76_97_fu_2714_p3;
reg   [7:0] p2_V_31_fu_466;
wire   [7:0] select_ln76_96_fu_2706_p3;
reg   [7:0] p2_V_30_fu_470;
wire   [7:0] select_ln76_95_fu_2698_p3;
reg   [7:0] p2_V_29_fu_474;
wire   [7:0] select_ln76_94_fu_2690_p3;
reg   [7:0] p2_V_28_fu_478;
wire   [7:0] select_ln76_93_fu_2682_p3;
reg   [7:0] p2_V_27_fu_482;
wire   [7:0] select_ln76_92_fu_2674_p3;
reg   [7:0] p2_V_26_fu_486;
wire   [7:0] select_ln76_91_fu_2666_p3;
reg   [7:0] p2_V_25_fu_490;
wire   [7:0] select_ln76_90_fu_2658_p3;
reg   [7:0] p2_V_24_fu_494;
wire   [7:0] select_ln76_89_fu_2650_p3;
reg   [7:0] p2_V_23_fu_498;
wire   [7:0] select_ln76_88_fu_2642_p3;
reg   [7:0] p2_V_22_fu_502;
wire   [7:0] select_ln76_87_fu_2634_p3;
reg   [7:0] p2_V_21_fu_506;
wire   [7:0] select_ln76_86_fu_2626_p3;
reg   [7:0] p2_V_20_fu_510;
wire   [7:0] select_ln76_85_fu_2618_p3;
reg   [7:0] p2_V_19_fu_514;
wire   [7:0] select_ln76_84_fu_2610_p3;
reg   [7:0] p2_V_18_fu_518;
wire   [7:0] select_ln76_83_fu_2602_p3;
reg   [7:0] p2_V_17_fu_522;
wire   [7:0] select_ln76_82_fu_2594_p3;
reg   [7:0] p2_V_16_fu_526;
wire   [7:0] select_ln76_81_fu_2586_p3;
reg   [7:0] p2_V_15_fu_530;
wire   [7:0] select_ln76_80_fu_2578_p3;
reg   [7:0] p2_V_14_fu_534;
wire   [7:0] select_ln76_79_fu_2570_p3;
reg   [7:0] p2_V_13_fu_538;
wire   [7:0] select_ln76_78_fu_2562_p3;
reg   [7:0] p2_V_12_fu_542;
wire   [7:0] select_ln76_77_fu_2554_p3;
reg   [7:0] p2_V_11_fu_546;
wire   [7:0] select_ln76_76_fu_2546_p3;
reg   [7:0] p2_V_10_fu_550;
wire   [7:0] select_ln76_75_fu_2538_p3;
reg   [7:0] p2_V_9_fu_554;
wire   [7:0] select_ln76_74_fu_2530_p3;
reg   [7:0] p2_V_8_fu_558;
wire   [7:0] select_ln76_73_fu_2522_p3;
reg   [7:0] p2_V_7_fu_562;
wire   [7:0] select_ln76_72_fu_2514_p3;
reg   [7:0] p2_V_6_fu_566;
wire   [7:0] select_ln76_71_fu_2506_p3;
reg   [7:0] p2_V_5_fu_570;
wire   [7:0] select_ln76_70_fu_2498_p3;
reg   [7:0] p2_V_4_fu_574;
wire   [7:0] select_ln76_69_fu_2490_p3;
reg   [7:0] p2_V_3_fu_578;
wire   [7:0] select_ln76_68_fu_2482_p3;
reg   [7:0] p2_V_2_fu_582;
wire   [7:0] select_ln76_67_fu_2474_p3;
reg   [7:0] p2_V_1_fu_586;
wire   [7:0] select_ln76_66_fu_2466_p3;
reg   [7:0] p2_V_fu_590;
wire   [7:0] select_ln76_65_fu_2458_p3;
reg   [7:0] p2_V_63_fu_594;
wire   [7:0] select_ln76_64_fu_2450_p3;
reg   [7:0] p2_V_64_fu_598;
wire   [7:0] select_ln76_63_fu_2442_p3;
reg   [7:0] p2_V_65_fu_602;
wire   [7:0] select_ln76_62_fu_2434_p3;
reg   [7:0] p2_V_66_fu_606;
wire   [7:0] select_ln76_61_fu_2426_p3;
reg   [7:0] p2_V_67_fu_610;
wire   [7:0] select_ln76_60_fu_2418_p3;
reg   [7:0] p2_V_68_fu_614;
wire   [7:0] select_ln76_59_fu_2410_p3;
reg   [7:0] p2_V_69_fu_618;
wire   [7:0] select_ln76_58_fu_2402_p3;
reg   [7:0] p2_V_70_fu_622;
wire   [7:0] select_ln76_57_fu_2394_p3;
reg   [7:0] p2_V_71_fu_626;
wire   [7:0] select_ln76_56_fu_2386_p3;
reg   [7:0] p2_V_72_fu_630;
wire   [7:0] select_ln76_55_fu_2378_p3;
reg   [7:0] p2_V_73_fu_634;
wire   [7:0] select_ln76_54_fu_2370_p3;
reg   [7:0] p2_V_74_fu_638;
wire   [7:0] select_ln76_53_fu_2362_p3;
reg   [7:0] p2_V_75_fu_642;
wire   [7:0] select_ln76_52_fu_2354_p3;
reg   [7:0] p2_V_76_fu_646;
wire   [7:0] select_ln76_51_fu_2346_p3;
reg   [7:0] p2_V_77_fu_650;
wire   [7:0] select_ln76_50_fu_2338_p3;
reg   [7:0] p2_V_78_fu_654;
wire   [7:0] select_ln76_49_fu_2330_p3;
reg   [7:0] p2_V_79_fu_658;
wire   [7:0] select_ln76_48_fu_2322_p3;
reg   [7:0] p2_V_80_fu_662;
wire   [7:0] select_ln76_47_fu_2314_p3;
reg   [7:0] p2_V_81_fu_666;
wire   [7:0] select_ln76_46_fu_2306_p3;
reg   [7:0] p2_V_82_fu_670;
wire   [7:0] select_ln76_45_fu_2298_p3;
reg   [7:0] p2_V_83_fu_674;
wire   [7:0] select_ln76_44_fu_2290_p3;
reg   [7:0] p2_V_84_fu_678;
wire   [7:0] select_ln76_43_fu_2282_p3;
reg   [7:0] p2_V_85_fu_682;
wire   [7:0] select_ln76_42_fu_2274_p3;
reg   [7:0] p2_V_86_fu_686;
wire   [7:0] select_ln76_41_fu_2266_p3;
reg   [7:0] p2_V_87_fu_690;
wire   [7:0] select_ln76_40_fu_2258_p3;
reg   [7:0] p2_V_88_fu_694;
wire   [7:0] select_ln76_39_fu_2250_p3;
reg   [7:0] p2_V_89_fu_698;
wire   [7:0] select_ln76_38_fu_2242_p3;
reg   [7:0] p2_V_90_fu_702;
wire   [7:0] select_ln76_37_fu_2234_p3;
reg   [7:0] p2_V_91_fu_706;
wire   [7:0] select_ln76_36_fu_2226_p3;
reg   [7:0] p2_V_92_fu_710;
wire   [7:0] select_ln76_35_fu_2218_p3;
reg   [7:0] p2_V_93_fu_714;
wire   [7:0] select_ln76_34_fu_2210_p3;
reg   [7:0] p2_V_94_fu_718;
wire   [7:0] select_ln76_33_fu_2202_p3;
reg   [7:0] p2_V_95_fu_722;
wire   [7:0] select_ln76_32_fu_2194_p3;
reg   [7:0] p2_V_96_fu_726;
wire   [7:0] select_ln76_31_fu_2186_p3;
reg   [7:0] p2_V_97_fu_730;
wire   [7:0] select_ln76_30_fu_2178_p3;
reg   [7:0] p2_V_98_fu_734;
wire   [7:0] select_ln76_29_fu_2170_p3;
reg   [7:0] p2_V_99_fu_738;
wire   [7:0] select_ln76_28_fu_2162_p3;
reg   [7:0] p2_V_100_fu_742;
wire   [7:0] select_ln76_27_fu_2154_p3;
reg   [7:0] p2_V_101_fu_746;
wire   [7:0] select_ln76_26_fu_2146_p3;
reg   [7:0] p2_V_102_fu_750;
wire   [7:0] select_ln76_25_fu_2138_p3;
reg   [7:0] p2_V_103_fu_754;
wire   [7:0] select_ln76_24_fu_2130_p3;
reg   [7:0] p2_V_104_fu_758;
wire   [7:0] select_ln76_23_fu_2122_p3;
reg   [7:0] p2_V_105_fu_762;
wire   [7:0] select_ln76_22_fu_2114_p3;
reg   [7:0] p2_V_106_fu_766;
wire   [7:0] select_ln76_21_fu_2106_p3;
reg   [7:0] p2_V_107_fu_770;
wire   [7:0] select_ln76_20_fu_2098_p3;
reg   [7:0] p2_V_108_fu_774;
wire   [7:0] select_ln76_19_fu_2090_p3;
reg   [7:0] p2_V_109_fu_778;
wire   [7:0] select_ln76_18_fu_2082_p3;
reg   [7:0] p2_V_110_fu_782;
wire   [7:0] select_ln76_17_fu_2074_p3;
reg   [7:0] p2_V_111_fu_786;
wire   [7:0] select_ln76_16_fu_2066_p3;
reg   [7:0] p2_V_112_fu_790;
wire   [7:0] select_ln76_15_fu_2058_p3;
reg   [7:0] p2_V_113_fu_794;
wire   [7:0] select_ln76_14_fu_2050_p3;
reg   [7:0] p2_V_114_fu_798;
wire   [7:0] select_ln76_13_fu_2042_p3;
reg   [7:0] p2_V_115_fu_802;
wire   [7:0] select_ln76_12_fu_2034_p3;
reg   [7:0] p2_V_116_fu_806;
wire   [7:0] select_ln76_11_fu_2026_p3;
reg   [7:0] p2_V_117_fu_810;
wire   [7:0] select_ln76_10_fu_2018_p3;
reg   [7:0] p2_V_118_fu_814;
wire   [7:0] select_ln76_9_fu_2010_p3;
reg   [7:0] p2_V_119_fu_818;
wire   [7:0] select_ln76_8_fu_2002_p3;
reg   [7:0] p2_V_120_fu_822;
wire   [7:0] select_ln76_7_fu_1994_p3;
reg   [7:0] p2_V_121_fu_826;
wire   [7:0] select_ln76_6_fu_1986_p3;
reg   [7:0] p2_V_122_fu_830;
wire   [7:0] select_ln76_5_fu_1978_p3;
reg   [7:0] p2_V_123_fu_834;
wire   [7:0] select_ln76_4_fu_1970_p3;
reg   [7:0] p2_V_124_fu_838;
wire   [7:0] select_ln76_3_fu_1962_p3;
reg   [7:0] p2_V_125_fu_842;
wire   [7:0] select_ln76_2_fu_1954_p3;
reg   [7:0] p2_V_126_fu_846;
wire   [7:0] select_ln76_1_fu_1946_p3;
reg   [7:0] p2_V_127_fu_850;
wire   [7:0] select_ln76_fu_1938_p3;
wire   [3:0] shl_ln80_1_fu_4396_p2;
wire   [7:0] p2_V_383_fu_1418_p4;
wire   [7:0] p2_V_382_fu_1408_p4;
wire   [7:0] p2_V_381_fu_1398_p4;
wire   [7:0] p2_V_380_fu_1928_p4;
wire   [7:0] p2_V_379_fu_1918_p4;
wire   [7:0] p2_V_378_fu_1908_p4;
wire   [7:0] p2_V_377_fu_1898_p4;
wire   [7:0] p2_V_376_fu_1888_p4;
wire   [7:0] p2_V_375_fu_1878_p4;
wire   [7:0] p2_V_374_fu_1868_p4;
wire   [7:0] p2_V_373_fu_1858_p4;
wire   [7:0] p2_V_372_fu_1388_p4;
wire   [7:0] p2_V_371_fu_1378_p4;
wire   [7:0] p2_V_370_fu_1368_p4;
wire   [7:0] p2_V_369_fu_1358_p4;
wire   [7:0] p2_V_368_fu_1348_p4;
wire   [7:0] p2_V_367_fu_1338_p4;
wire   [7:0] p2_V_366_fu_1328_p4;
wire   [7:0] p2_V_365_fu_1318_p4;
wire   [7:0] p2_V_364_fu_1848_p4;
wire   [7:0] p2_V_363_fu_1838_p4;
wire   [7:0] p2_V_362_fu_1828_p4;
wire   [7:0] p2_V_361_fu_1818_p4;
wire   [7:0] p2_V_360_fu_1808_p4;
wire   [7:0] p2_V_359_fu_1798_p4;
wire   [7:0] p2_V_358_fu_1788_p4;
wire   [7:0] p2_V_357_fu_1778_p4;
wire   [7:0] p2_V_356_fu_1768_p4;
wire   [7:0] p2_V_355_fu_1758_p4;
wire   [7:0] p2_V_354_fu_1748_p4;
wire   [7:0] p2_V_353_fu_1738_p4;
wire   [7:0] p2_V_352_fu_1728_p4;
wire   [7:0] p2_V_351_fu_1718_p4;
wire   [7:0] p2_V_350_fu_1308_p4;
wire   [7:0] p2_V_349_fu_1708_p4;
wire   [7:0] p2_V_348_fu_1698_p4;
wire   [7:0] p2_V_347_fu_1688_p4;
wire   [7:0] p2_V_346_fu_1678_p4;
wire   [7:0] p2_V_345_fu_1668_p4;
wire   [7:0] p2_V_344_fu_1658_p4;
wire   [7:0] p2_V_343_fu_1648_p4;
wire   [7:0] p2_V_342_fu_1638_p4;
wire   [7:0] p2_V_341_fu_1628_p4;
wire   [7:0] p2_V_340_fu_1618_p4;
wire   [7:0] p2_V_339_fu_1608_p4;
wire   [7:0] p2_V_338_fu_1598_p4;
wire   [7:0] p2_V_337_fu_1588_p4;
wire   [7:0] p2_V_336_fu_1578_p4;
wire   [7:0] p2_V_335_fu_1568_p4;
wire   [7:0] p2_V_334_fu_1558_p4;
wire   [7:0] p2_V_333_fu_1548_p4;
wire   [7:0] p2_V_332_fu_1538_p4;
wire   [7:0] p2_V_331_fu_1528_p4;
wire   [7:0] p2_V_330_fu_1518_p4;
wire   [7:0] p2_V_329_fu_1508_p4;
wire   [7:0] p2_V_328_fu_1498_p4;
wire   [7:0] p2_V_327_fu_1488_p4;
wire   [7:0] p2_V_326_fu_1478_p4;
wire   [7:0] p2_V_325_fu_1468_p4;
wire   [7:0] p2_V_324_fu_1458_p4;
wire   [7:0] p2_V_323_fu_1448_p4;
wire   [7:0] p2_V_322_fu_1438_p4;
wire   [7:0] p2_V_321_fu_1428_p4;
wire   [7:0] p2_V_320_fu_1304_p1;
wire   [10:0] tmp_7_fu_3997_p3;
wire   [8:0] tmp_8_fu_4008_p3;
wire   [11:0] zext_ln80_fu_4004_p1;
wire   [11:0] zext_ln80_1_fu_4015_p1;
wire   [11:0] add_ln80_fu_4019_p2;
wire   [32:0] zext_ln80_2_fu_4025_p1;
wire   [32:0] zext_ln80_3_fu_4029_p1;
wire   [32:0] add_ln80_1_fu_4033_p2;
wire   [11:0] trunc_ln80_fu_4039_p1;
wire   [13:0] trunc_ln80_1_fu_4051_p1;
wire   [14:0] p_shl_fu_4043_p3;
wire   [14:0] p_shl1_fu_4055_p3;
wire   [1:0] trunc_ln80_2_fu_4069_p1;
wire   [14:0] add_ln80_2_fu_4063_p2;
wire   [14:0] lshr_ln_fu_4081_p4;
wire   [14:0] add_ln80_3_fu_4091_p2;
wire   [7:0] tmp_fu_4102_p66;
wire   [7:0] tmp_s_fu_4235_p66;
wire   [4:0] shl_ln_fu_4073_p3;
wire   [7:0] tmp_1_fu_4368_p4;
wire   [31:0] zext_ln80_6_fu_4381_p1;
wire   [31:0] zext_ln80_5_fu_4377_p1;
wire   [3:0] zext_ln80_7_fu_4392_p1;
wire   [31:0] w_3_fu_4408_p2;
wire   [0:0] icmp_ln82_1_fu_4414_p2;
wire   [31:0] add_ln82_fu_4420_p2;
wire   [0:0] icmp_ln82_fu_4403_p2;
wire   [31:0] w_4_fu_4426_p3;
wire   [31:0] h_2_fu_4434_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

concat_channel_stream_mux_646_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
mux_646_8_1_1_U13(
    .din0(p2_V_62_fu_342),
    .din1(p2_V_61_fu_346),
    .din2(p2_V_60_fu_350),
    .din3(p2_V_59_fu_354),
    .din4(p2_V_58_fu_358),
    .din5(p2_V_57_fu_362),
    .din6(p2_V_56_fu_366),
    .din7(p2_V_55_fu_370),
    .din8(p2_V_54_fu_374),
    .din9(p2_V_53_fu_378),
    .din10(p2_V_52_fu_382),
    .din11(p2_V_51_fu_386),
    .din12(p2_V_50_fu_390),
    .din13(p2_V_49_fu_394),
    .din14(p2_V_48_fu_398),
    .din15(p2_V_47_fu_402),
    .din16(p2_V_46_fu_406),
    .din17(p2_V_45_fu_410),
    .din18(p2_V_44_fu_414),
    .din19(p2_V_43_fu_418),
    .din20(p2_V_42_fu_422),
    .din21(p2_V_41_fu_426),
    .din22(p2_V_40_fu_430),
    .din23(p2_V_39_fu_434),
    .din24(p2_V_38_fu_438),
    .din25(p2_V_37_fu_442),
    .din26(p2_V_36_fu_446),
    .din27(p2_V_35_fu_450),
    .din28(p2_V_34_fu_454),
    .din29(p2_V_33_fu_458),
    .din30(p2_V_32_fu_462),
    .din31(p2_V_31_fu_466),
    .din32(p2_V_30_fu_470),
    .din33(p2_V_29_fu_474),
    .din34(p2_V_28_fu_478),
    .din35(p2_V_27_fu_482),
    .din36(p2_V_26_fu_486),
    .din37(p2_V_25_fu_490),
    .din38(p2_V_24_fu_494),
    .din39(p2_V_23_fu_498),
    .din40(p2_V_22_fu_502),
    .din41(p2_V_21_fu_506),
    .din42(p2_V_20_fu_510),
    .din43(p2_V_19_fu_514),
    .din44(p2_V_18_fu_518),
    .din45(p2_V_17_fu_522),
    .din46(p2_V_16_fu_526),
    .din47(p2_V_15_fu_530),
    .din48(p2_V_14_fu_534),
    .din49(p2_V_13_fu_538),
    .din50(p2_V_12_fu_542),
    .din51(p2_V_11_fu_546),
    .din52(p2_V_10_fu_550),
    .din53(p2_V_9_fu_554),
    .din54(p2_V_8_fu_558),
    .din55(p2_V_7_fu_562),
    .din56(p2_V_6_fu_566),
    .din57(p2_V_5_fu_570),
    .din58(p2_V_4_fu_574),
    .din59(p2_V_3_fu_578),
    .din60(p2_V_2_fu_582),
    .din61(p2_V_1_fu_586),
    .din62(p2_V_fu_590),
    .din63(p2_V_63_fu_594),
    .din64(c_reg_5388),
    .dout(tmp_fu_4102_p66)
);

concat_channel_stream_mux_646_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
mux_646_8_1_1_U14(
    .din0(p2_V_64_fu_598),
    .din1(p2_V_65_fu_602),
    .din2(p2_V_66_fu_606),
    .din3(p2_V_67_fu_610),
    .din4(p2_V_68_fu_614),
    .din5(p2_V_69_fu_618),
    .din6(p2_V_70_fu_622),
    .din7(p2_V_71_fu_626),
    .din8(p2_V_72_fu_630),
    .din9(p2_V_73_fu_634),
    .din10(p2_V_74_fu_638),
    .din11(p2_V_75_fu_642),
    .din12(p2_V_76_fu_646),
    .din13(p2_V_77_fu_650),
    .din14(p2_V_78_fu_654),
    .din15(p2_V_79_fu_658),
    .din16(p2_V_80_fu_662),
    .din17(p2_V_81_fu_666),
    .din18(p2_V_82_fu_670),
    .din19(p2_V_83_fu_674),
    .din20(p2_V_84_fu_678),
    .din21(p2_V_85_fu_682),
    .din22(p2_V_86_fu_686),
    .din23(p2_V_87_fu_690),
    .din24(p2_V_88_fu_694),
    .din25(p2_V_89_fu_698),
    .din26(p2_V_90_fu_702),
    .din27(p2_V_91_fu_706),
    .din28(p2_V_92_fu_710),
    .din29(p2_V_93_fu_714),
    .din30(p2_V_94_fu_718),
    .din31(p2_V_95_fu_722),
    .din32(p2_V_96_fu_726),
    .din33(p2_V_97_fu_730),
    .din34(p2_V_98_fu_734),
    .din35(p2_V_99_fu_738),
    .din36(p2_V_100_fu_742),
    .din37(p2_V_101_fu_746),
    .din38(p2_V_102_fu_750),
    .din39(p2_V_103_fu_754),
    .din40(p2_V_104_fu_758),
    .din41(p2_V_105_fu_762),
    .din42(p2_V_106_fu_766),
    .din43(p2_V_107_fu_770),
    .din44(p2_V_108_fu_774),
    .din45(p2_V_109_fu_778),
    .din46(p2_V_110_fu_782),
    .din47(p2_V_111_fu_786),
    .din48(p2_V_112_fu_790),
    .din49(p2_V_113_fu_794),
    .din50(p2_V_114_fu_798),
    .din51(p2_V_115_fu_802),
    .din52(p2_V_116_fu_806),
    .din53(p2_V_117_fu_810),
    .din54(p2_V_118_fu_814),
    .din55(p2_V_119_fu_818),
    .din56(p2_V_120_fu_822),
    .din57(p2_V_121_fu_826),
    .din58(p2_V_122_fu_830),
    .din59(p2_V_123_fu_834),
    .din60(p2_V_124_fu_838),
    .din61(p2_V_125_fu_842),
    .din62(p2_V_126_fu_846),
    .din63(p2_V_127_fu_850),
    .din64(c_reg_5388),
    .dout(tmp_s_fu_4235_p66)
);

concat_channel_stream_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U15(
    .din0(tmp_fu_4102_p66),
    .din1(tmp_s_fu_4235_p66),
    .din2(tmp_11_reg_5397),
    .dout(tmp_1_fu_4368_p4)
);

concat_channel_stream_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_fu_338 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            h_fu_338 <= h_3_fu_4450_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln67_fu_890_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            t_fu_330 <= t_4_fu_896_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_330 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_334 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            w_fu_334 <= w_5_fu_4442_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln67_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_reg_5388 <= c_fu_902_p1;
        tmp_11_reg_5397 <= ap_sig_allocacmp_t_3[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln72_fu_914_p2 == 1'd1) & (icmp_ln67_fu_890_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p2_V_100_fu_742 <= select_ln76_27_fu_2154_p3;
        p2_V_101_fu_746 <= select_ln76_26_fu_2146_p3;
        p2_V_102_fu_750 <= select_ln76_25_fu_2138_p3;
        p2_V_103_fu_754 <= select_ln76_24_fu_2130_p3;
        p2_V_104_fu_758 <= select_ln76_23_fu_2122_p3;
        p2_V_105_fu_762 <= select_ln76_22_fu_2114_p3;
        p2_V_106_fu_766 <= select_ln76_21_fu_2106_p3;
        p2_V_107_fu_770 <= select_ln76_20_fu_2098_p3;
        p2_V_108_fu_774 <= select_ln76_19_fu_2090_p3;
        p2_V_109_fu_778 <= select_ln76_18_fu_2082_p3;
        p2_V_10_fu_550 <= select_ln76_75_fu_2538_p3;
        p2_V_110_fu_782 <= select_ln76_17_fu_2074_p3;
        p2_V_111_fu_786 <= select_ln76_16_fu_2066_p3;
        p2_V_112_fu_790 <= select_ln76_15_fu_2058_p3;
        p2_V_113_fu_794 <= select_ln76_14_fu_2050_p3;
        p2_V_114_fu_798 <= select_ln76_13_fu_2042_p3;
        p2_V_115_fu_802 <= select_ln76_12_fu_2034_p3;
        p2_V_116_fu_806 <= select_ln76_11_fu_2026_p3;
        p2_V_117_fu_810 <= select_ln76_10_fu_2018_p3;
        p2_V_118_fu_814 <= select_ln76_9_fu_2010_p3;
        p2_V_119_fu_818 <= select_ln76_8_fu_2002_p3;
        p2_V_11_fu_546 <= select_ln76_76_fu_2546_p3;
        p2_V_120_fu_822 <= select_ln76_7_fu_1994_p3;
        p2_V_121_fu_826 <= select_ln76_6_fu_1986_p3;
        p2_V_122_fu_830 <= select_ln76_5_fu_1978_p3;
        p2_V_123_fu_834 <= select_ln76_4_fu_1970_p3;
        p2_V_124_fu_838 <= select_ln76_3_fu_1962_p3;
        p2_V_125_fu_842 <= select_ln76_2_fu_1954_p3;
        p2_V_126_fu_846 <= select_ln76_1_fu_1946_p3;
        p2_V_127_fu_850 <= select_ln76_fu_1938_p3;
        p2_V_12_fu_542 <= select_ln76_77_fu_2554_p3;
        p2_V_13_fu_538 <= select_ln76_78_fu_2562_p3;
        p2_V_14_fu_534 <= select_ln76_79_fu_2570_p3;
        p2_V_15_fu_530 <= select_ln76_80_fu_2578_p3;
        p2_V_16_fu_526 <= select_ln76_81_fu_2586_p3;
        p2_V_17_fu_522 <= select_ln76_82_fu_2594_p3;
        p2_V_18_fu_518 <= select_ln76_83_fu_2602_p3;
        p2_V_19_fu_514 <= select_ln76_84_fu_2610_p3;
        p2_V_1_fu_586 <= select_ln76_66_fu_2466_p3;
        p2_V_20_fu_510 <= select_ln76_85_fu_2618_p3;
        p2_V_21_fu_506 <= select_ln76_86_fu_2626_p3;
        p2_V_22_fu_502 <= select_ln76_87_fu_2634_p3;
        p2_V_23_fu_498 <= select_ln76_88_fu_2642_p3;
        p2_V_24_fu_494 <= select_ln76_89_fu_2650_p3;
        p2_V_25_fu_490 <= select_ln76_90_fu_2658_p3;
        p2_V_26_fu_486 <= select_ln76_91_fu_2666_p3;
        p2_V_27_fu_482 <= select_ln76_92_fu_2674_p3;
        p2_V_28_fu_478 <= select_ln76_93_fu_2682_p3;
        p2_V_29_fu_474 <= select_ln76_94_fu_2690_p3;
        p2_V_2_fu_582 <= select_ln76_67_fu_2474_p3;
        p2_V_30_fu_470 <= select_ln76_95_fu_2698_p3;
        p2_V_31_fu_466 <= select_ln76_96_fu_2706_p3;
        p2_V_32_fu_462 <= select_ln76_97_fu_2714_p3;
        p2_V_33_fu_458 <= select_ln76_98_fu_2722_p3;
        p2_V_34_fu_454 <= select_ln76_99_fu_2730_p3;
        p2_V_35_fu_450 <= select_ln76_100_fu_2738_p3;
        p2_V_36_fu_446 <= select_ln76_101_fu_2746_p3;
        p2_V_37_fu_442 <= select_ln76_102_fu_2754_p3;
        p2_V_38_fu_438 <= select_ln76_103_fu_2762_p3;
        p2_V_39_fu_434 <= select_ln76_104_fu_2770_p3;
        p2_V_3_fu_578 <= select_ln76_68_fu_2482_p3;
        p2_V_40_fu_430 <= select_ln76_105_fu_2778_p3;
        p2_V_41_fu_426 <= select_ln76_106_fu_2786_p3;
        p2_V_42_fu_422 <= select_ln76_107_fu_2794_p3;
        p2_V_43_fu_418 <= select_ln76_108_fu_2802_p3;
        p2_V_44_fu_414 <= select_ln76_109_fu_2810_p3;
        p2_V_45_fu_410 <= select_ln76_110_fu_2818_p3;
        p2_V_46_fu_406 <= select_ln76_111_fu_2826_p3;
        p2_V_47_fu_402 <= select_ln76_112_fu_2834_p3;
        p2_V_48_fu_398 <= select_ln76_113_fu_2842_p3;
        p2_V_49_fu_394 <= select_ln76_114_fu_2850_p3;
        p2_V_4_fu_574 <= select_ln76_69_fu_2490_p3;
        p2_V_50_fu_390 <= select_ln76_115_fu_2858_p3;
        p2_V_51_fu_386 <= select_ln76_116_fu_2866_p3;
        p2_V_52_fu_382 <= select_ln76_117_fu_2874_p3;
        p2_V_53_fu_378 <= select_ln76_118_fu_2882_p3;
        p2_V_54_fu_374 <= select_ln76_119_fu_2890_p3;
        p2_V_55_fu_370 <= select_ln76_120_fu_2898_p3;
        p2_V_56_fu_366 <= select_ln76_121_fu_2906_p3;
        p2_V_57_fu_362 <= select_ln76_122_fu_2914_p3;
        p2_V_58_fu_358 <= select_ln76_123_fu_2922_p3;
        p2_V_59_fu_354 <= select_ln76_124_fu_2930_p3;
        p2_V_5_fu_570 <= select_ln76_70_fu_2498_p3;
        p2_V_60_fu_350 <= select_ln76_125_fu_2938_p3;
        p2_V_61_fu_346 <= select_ln76_126_fu_2946_p3;
        p2_V_62_fu_342 <= select_ln76_127_fu_2954_p3;
        p2_V_63_fu_594 <= select_ln76_64_fu_2450_p3;
        p2_V_64_fu_598 <= select_ln76_63_fu_2442_p3;
        p2_V_65_fu_602 <= select_ln76_62_fu_2434_p3;
        p2_V_66_fu_606 <= select_ln76_61_fu_2426_p3;
        p2_V_67_fu_610 <= select_ln76_60_fu_2418_p3;
        p2_V_68_fu_614 <= select_ln76_59_fu_2410_p3;
        p2_V_69_fu_618 <= select_ln76_58_fu_2402_p3;
        p2_V_6_fu_566 <= select_ln76_71_fu_2506_p3;
        p2_V_70_fu_622 <= select_ln76_57_fu_2394_p3;
        p2_V_71_fu_626 <= select_ln76_56_fu_2386_p3;
        p2_V_72_fu_630 <= select_ln76_55_fu_2378_p3;
        p2_V_73_fu_634 <= select_ln76_54_fu_2370_p3;
        p2_V_74_fu_638 <= select_ln76_53_fu_2362_p3;
        p2_V_75_fu_642 <= select_ln76_52_fu_2354_p3;
        p2_V_76_fu_646 <= select_ln76_51_fu_2346_p3;
        p2_V_77_fu_650 <= select_ln76_50_fu_2338_p3;
        p2_V_78_fu_654 <= select_ln76_49_fu_2330_p3;
        p2_V_79_fu_658 <= select_ln76_48_fu_2322_p3;
        p2_V_7_fu_562 <= select_ln76_72_fu_2514_p3;
        p2_V_80_fu_662 <= select_ln76_47_fu_2314_p3;
        p2_V_81_fu_666 <= select_ln76_46_fu_2306_p3;
        p2_V_82_fu_670 <= select_ln76_45_fu_2298_p3;
        p2_V_83_fu_674 <= select_ln76_44_fu_2290_p3;
        p2_V_84_fu_678 <= select_ln76_43_fu_2282_p3;
        p2_V_85_fu_682 <= select_ln76_42_fu_2274_p3;
        p2_V_86_fu_686 <= select_ln76_41_fu_2266_p3;
        p2_V_87_fu_690 <= select_ln76_40_fu_2258_p3;
        p2_V_88_fu_694 <= select_ln76_39_fu_2250_p3;
        p2_V_89_fu_698 <= select_ln76_38_fu_2242_p3;
        p2_V_8_fu_558 <= select_ln76_73_fu_2522_p3;
        p2_V_90_fu_702 <= select_ln76_37_fu_2234_p3;
        p2_V_91_fu_706 <= select_ln76_36_fu_2226_p3;
        p2_V_92_fu_710 <= select_ln76_35_fu_2218_p3;
        p2_V_93_fu_714 <= select_ln76_34_fu_2210_p3;
        p2_V_94_fu_718 <= select_ln76_33_fu_2202_p3;
        p2_V_95_fu_722 <= select_ln76_32_fu_2194_p3;
        p2_V_96_fu_726 <= select_ln76_31_fu_2186_p3;
        p2_V_97_fu_730 <= select_ln76_30_fu_2178_p3;
        p2_V_98_fu_734 <= select_ln76_29_fu_2170_p3;
        p2_V_99_fu_738 <= select_ln76_28_fu_2162_p3;
        p2_V_9_fu_554 <= select_ln76_74_fu_2530_p3;
        p2_V_fu_590 <= select_ln76_65_fu_2458_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln67_fu_890_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_3 = 17'd0;
    end else begin
        ap_sig_allocacmp_t_3 = t_fu_330;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y2_buf_ce0 = 1'b1;
    end else begin
        y2_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y2_buf_we0 = shl_ln80_1_fu_4396_p2;
    end else begin
        y2_buf_we0 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op280_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y2_s_TDATA_blk_n = y2_s_TVALID;
    end else begin
        y2_s_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op280_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y2_s_TREADY = 1'b1;
    end else begin
        y2_s_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln80_1_fu_4033_p2 = (zext_ln80_2_fu_4025_p1 + zext_ln80_3_fu_4029_p1);

assign add_ln80_2_fu_4063_p2 = (p_shl_fu_4043_p3 + p_shl1_fu_4055_p3);

assign add_ln80_3_fu_4091_p2 = (add_ln80_2_fu_4063_p2 + lshr_ln_fu_4081_p4);

assign add_ln80_fu_4019_p2 = (zext_ln80_fu_4004_p1 + zext_ln80_1_fu_4015_p1);

assign add_ln82_fu_4420_p2 = (h_fu_338 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_predicate_op280_read_state1 == 1'b1) & (y2_s_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_predicate_op280_read_state1 == 1'b1) & (y2_s_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op280_read_state1 == 1'b1) & (y2_s_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op280_read_state1 = ((icmp_ln72_fu_914_p2 == 1'd1) & (icmp_ln67_fu_890_p2 == 1'd0));
end

assign c_fu_902_p1 = ap_sig_allocacmp_t_3[5:0];

assign h_2_fu_4434_p3 = ((icmp_ln82_1_fu_4414_p2[0:0] == 1'b1) ? add_ln82_fu_4420_p2 : h_fu_338);

assign h_3_fu_4450_p3 = ((icmp_ln82_fu_4403_p2[0:0] == 1'b1) ? h_2_fu_4434_p3 : h_fu_338);

assign icmp_ln67_fu_890_p2 = ((ap_sig_allocacmp_t_3 == 17'd102400) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_914_p2 = ((c_fu_902_p1 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln82_1_fu_4414_p2 = ((w_3_fu_4408_p2 == 32'd40) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_4403_p2 = ((c_reg_5388 == 6'd63) ? 1'b1 : 1'b0);

assign lshr_ln_fu_4081_p4 = {{w_fu_334[16:2]}};

assign p2_V_320_fu_1304_p1 = y2_s_TDATA[7:0];

assign p2_V_321_fu_1428_p4 = {{y2_s_TDATA[15:8]}};

assign p2_V_322_fu_1438_p4 = {{y2_s_TDATA[23:16]}};

assign p2_V_323_fu_1448_p4 = {{y2_s_TDATA[31:24]}};

assign p2_V_324_fu_1458_p4 = {{y2_s_TDATA[39:32]}};

assign p2_V_325_fu_1468_p4 = {{y2_s_TDATA[47:40]}};

assign p2_V_326_fu_1478_p4 = {{y2_s_TDATA[55:48]}};

assign p2_V_327_fu_1488_p4 = {{y2_s_TDATA[63:56]}};

assign p2_V_328_fu_1498_p4 = {{y2_s_TDATA[71:64]}};

assign p2_V_329_fu_1508_p4 = {{y2_s_TDATA[79:72]}};

assign p2_V_330_fu_1518_p4 = {{y2_s_TDATA[87:80]}};

assign p2_V_331_fu_1528_p4 = {{y2_s_TDATA[95:88]}};

assign p2_V_332_fu_1538_p4 = {{y2_s_TDATA[103:96]}};

assign p2_V_333_fu_1548_p4 = {{y2_s_TDATA[111:104]}};

assign p2_V_334_fu_1558_p4 = {{y2_s_TDATA[119:112]}};

assign p2_V_335_fu_1568_p4 = {{y2_s_TDATA[127:120]}};

assign p2_V_336_fu_1578_p4 = {{y2_s_TDATA[135:128]}};

assign p2_V_337_fu_1588_p4 = {{y2_s_TDATA[143:136]}};

assign p2_V_338_fu_1598_p4 = {{y2_s_TDATA[151:144]}};

assign p2_V_339_fu_1608_p4 = {{y2_s_TDATA[159:152]}};

assign p2_V_340_fu_1618_p4 = {{y2_s_TDATA[167:160]}};

assign p2_V_341_fu_1628_p4 = {{y2_s_TDATA[175:168]}};

assign p2_V_342_fu_1638_p4 = {{y2_s_TDATA[183:176]}};

assign p2_V_343_fu_1648_p4 = {{y2_s_TDATA[191:184]}};

assign p2_V_344_fu_1658_p4 = {{y2_s_TDATA[199:192]}};

assign p2_V_345_fu_1668_p4 = {{y2_s_TDATA[207:200]}};

assign p2_V_346_fu_1678_p4 = {{y2_s_TDATA[215:208]}};

assign p2_V_347_fu_1688_p4 = {{y2_s_TDATA[223:216]}};

assign p2_V_348_fu_1698_p4 = {{y2_s_TDATA[231:224]}};

assign p2_V_349_fu_1708_p4 = {{y2_s_TDATA[239:232]}};

assign p2_V_350_fu_1308_p4 = {{y2_s_TDATA[247:240]}};

assign p2_V_351_fu_1718_p4 = {{y2_s_TDATA[255:248]}};

assign p2_V_352_fu_1728_p4 = {{y2_s_TDATA[263:256]}};

assign p2_V_353_fu_1738_p4 = {{y2_s_TDATA[271:264]}};

assign p2_V_354_fu_1748_p4 = {{y2_s_TDATA[279:272]}};

assign p2_V_355_fu_1758_p4 = {{y2_s_TDATA[287:280]}};

assign p2_V_356_fu_1768_p4 = {{y2_s_TDATA[295:288]}};

assign p2_V_357_fu_1778_p4 = {{y2_s_TDATA[303:296]}};

assign p2_V_358_fu_1788_p4 = {{y2_s_TDATA[311:304]}};

assign p2_V_359_fu_1798_p4 = {{y2_s_TDATA[319:312]}};

assign p2_V_360_fu_1808_p4 = {{y2_s_TDATA[327:320]}};

assign p2_V_361_fu_1818_p4 = {{y2_s_TDATA[335:328]}};

assign p2_V_362_fu_1828_p4 = {{y2_s_TDATA[343:336]}};

assign p2_V_363_fu_1838_p4 = {{y2_s_TDATA[351:344]}};

assign p2_V_364_fu_1848_p4 = {{y2_s_TDATA[359:352]}};

assign p2_V_365_fu_1318_p4 = {{y2_s_TDATA[367:360]}};

assign p2_V_366_fu_1328_p4 = {{y2_s_TDATA[375:368]}};

assign p2_V_367_fu_1338_p4 = {{y2_s_TDATA[383:376]}};

assign p2_V_368_fu_1348_p4 = {{y2_s_TDATA[391:384]}};

assign p2_V_369_fu_1358_p4 = {{y2_s_TDATA[399:392]}};

assign p2_V_370_fu_1368_p4 = {{y2_s_TDATA[407:400]}};

assign p2_V_371_fu_1378_p4 = {{y2_s_TDATA[415:408]}};

assign p2_V_372_fu_1388_p4 = {{y2_s_TDATA[423:416]}};

assign p2_V_373_fu_1858_p4 = {{y2_s_TDATA[431:424]}};

assign p2_V_374_fu_1868_p4 = {{y2_s_TDATA[439:432]}};

assign p2_V_375_fu_1878_p4 = {{y2_s_TDATA[447:440]}};

assign p2_V_376_fu_1888_p4 = {{y2_s_TDATA[455:448]}};

assign p2_V_377_fu_1898_p4 = {{y2_s_TDATA[463:456]}};

assign p2_V_378_fu_1908_p4 = {{y2_s_TDATA[471:464]}};

assign p2_V_379_fu_1918_p4 = {{y2_s_TDATA[479:472]}};

assign p2_V_380_fu_1928_p4 = {{y2_s_TDATA[487:480]}};

assign p2_V_381_fu_1398_p4 = {{y2_s_TDATA[495:488]}};

assign p2_V_382_fu_1408_p4 = {{y2_s_TDATA[503:496]}};

assign p2_V_383_fu_1418_p4 = {{y2_s_TDATA[511:504]}};

assign p_shl1_fu_4055_p3 = {{trunc_ln80_1_fu_4051_p1}, {1'd0}};

assign p_shl_fu_4043_p3 = {{trunc_ln80_fu_4039_p1}, {3'd0}};

assign select_ln76_100_fu_2738_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_35_fu_450 : p2_V_347_fu_1688_p4);

assign select_ln76_101_fu_2746_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_36_fu_446 : p2_V_346_fu_1678_p4);

assign select_ln76_102_fu_2754_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_37_fu_442 : p2_V_345_fu_1668_p4);

assign select_ln76_103_fu_2762_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_38_fu_438 : p2_V_344_fu_1658_p4);

assign select_ln76_104_fu_2770_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_39_fu_434 : p2_V_343_fu_1648_p4);

assign select_ln76_105_fu_2778_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_40_fu_430 : p2_V_342_fu_1638_p4);

assign select_ln76_106_fu_2786_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_41_fu_426 : p2_V_341_fu_1628_p4);

assign select_ln76_107_fu_2794_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_42_fu_422 : p2_V_340_fu_1618_p4);

assign select_ln76_108_fu_2802_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_43_fu_418 : p2_V_339_fu_1608_p4);

assign select_ln76_109_fu_2810_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_44_fu_414 : p2_V_338_fu_1598_p4);

assign select_ln76_10_fu_2018_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_373_fu_1858_p4 : p2_V_117_fu_810);

assign select_ln76_110_fu_2818_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_45_fu_410 : p2_V_337_fu_1588_p4);

assign select_ln76_111_fu_2826_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_46_fu_406 : p2_V_336_fu_1578_p4);

assign select_ln76_112_fu_2834_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_47_fu_402 : p2_V_335_fu_1568_p4);

assign select_ln76_113_fu_2842_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_48_fu_398 : p2_V_334_fu_1558_p4);

assign select_ln76_114_fu_2850_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_49_fu_394 : p2_V_333_fu_1548_p4);

assign select_ln76_115_fu_2858_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_50_fu_390 : p2_V_332_fu_1538_p4);

assign select_ln76_116_fu_2866_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_51_fu_386 : p2_V_331_fu_1528_p4);

assign select_ln76_117_fu_2874_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_52_fu_382 : p2_V_330_fu_1518_p4);

assign select_ln76_118_fu_2882_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_53_fu_378 : p2_V_329_fu_1508_p4);

assign select_ln76_119_fu_2890_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_54_fu_374 : p2_V_328_fu_1498_p4);

assign select_ln76_11_fu_2026_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_372_fu_1388_p4 : p2_V_116_fu_806);

assign select_ln76_120_fu_2898_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_55_fu_370 : p2_V_327_fu_1488_p4);

assign select_ln76_121_fu_2906_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_56_fu_366 : p2_V_326_fu_1478_p4);

assign select_ln76_122_fu_2914_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_57_fu_362 : p2_V_325_fu_1468_p4);

assign select_ln76_123_fu_2922_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_58_fu_358 : p2_V_324_fu_1458_p4);

assign select_ln76_124_fu_2930_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_59_fu_354 : p2_V_323_fu_1448_p4);

assign select_ln76_125_fu_2938_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_60_fu_350 : p2_V_322_fu_1438_p4);

assign select_ln76_126_fu_2946_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_61_fu_346 : p2_V_321_fu_1428_p4);

assign select_ln76_127_fu_2954_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_62_fu_342 : p2_V_320_fu_1304_p1);

assign select_ln76_12_fu_2034_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_371_fu_1378_p4 : p2_V_115_fu_802);

assign select_ln76_13_fu_2042_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_370_fu_1368_p4 : p2_V_114_fu_798);

assign select_ln76_14_fu_2050_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_369_fu_1358_p4 : p2_V_113_fu_794);

assign select_ln76_15_fu_2058_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_368_fu_1348_p4 : p2_V_112_fu_790);

assign select_ln76_16_fu_2066_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_367_fu_1338_p4 : p2_V_111_fu_786);

assign select_ln76_17_fu_2074_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_366_fu_1328_p4 : p2_V_110_fu_782);

assign select_ln76_18_fu_2082_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_365_fu_1318_p4 : p2_V_109_fu_778);

assign select_ln76_19_fu_2090_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_364_fu_1848_p4 : p2_V_108_fu_774);

assign select_ln76_1_fu_1946_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_382_fu_1408_p4 : p2_V_126_fu_846);

assign select_ln76_20_fu_2098_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_363_fu_1838_p4 : p2_V_107_fu_770);

assign select_ln76_21_fu_2106_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_362_fu_1828_p4 : p2_V_106_fu_766);

assign select_ln76_22_fu_2114_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_361_fu_1818_p4 : p2_V_105_fu_762);

assign select_ln76_23_fu_2122_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_360_fu_1808_p4 : p2_V_104_fu_758);

assign select_ln76_24_fu_2130_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_359_fu_1798_p4 : p2_V_103_fu_754);

assign select_ln76_25_fu_2138_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_358_fu_1788_p4 : p2_V_102_fu_750);

assign select_ln76_26_fu_2146_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_357_fu_1778_p4 : p2_V_101_fu_746);

assign select_ln76_27_fu_2154_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_356_fu_1768_p4 : p2_V_100_fu_742);

assign select_ln76_28_fu_2162_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_355_fu_1758_p4 : p2_V_99_fu_738);

assign select_ln76_29_fu_2170_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_354_fu_1748_p4 : p2_V_98_fu_734);

assign select_ln76_2_fu_1954_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_381_fu_1398_p4 : p2_V_125_fu_842);

assign select_ln76_30_fu_2178_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_353_fu_1738_p4 : p2_V_97_fu_730);

assign select_ln76_31_fu_2186_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_352_fu_1728_p4 : p2_V_96_fu_726);

assign select_ln76_32_fu_2194_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_351_fu_1718_p4 : p2_V_95_fu_722);

assign select_ln76_33_fu_2202_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_350_fu_1308_p4 : p2_V_94_fu_718);

assign select_ln76_34_fu_2210_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_349_fu_1708_p4 : p2_V_93_fu_714);

assign select_ln76_35_fu_2218_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_348_fu_1698_p4 : p2_V_92_fu_710);

assign select_ln76_36_fu_2226_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_347_fu_1688_p4 : p2_V_91_fu_706);

assign select_ln76_37_fu_2234_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_346_fu_1678_p4 : p2_V_90_fu_702);

assign select_ln76_38_fu_2242_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_345_fu_1668_p4 : p2_V_89_fu_698);

assign select_ln76_39_fu_2250_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_344_fu_1658_p4 : p2_V_88_fu_694);

assign select_ln76_3_fu_1962_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_380_fu_1928_p4 : p2_V_124_fu_838);

assign select_ln76_40_fu_2258_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_343_fu_1648_p4 : p2_V_87_fu_690);

assign select_ln76_41_fu_2266_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_342_fu_1638_p4 : p2_V_86_fu_686);

assign select_ln76_42_fu_2274_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_341_fu_1628_p4 : p2_V_85_fu_682);

assign select_ln76_43_fu_2282_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_340_fu_1618_p4 : p2_V_84_fu_678);

assign select_ln76_44_fu_2290_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_339_fu_1608_p4 : p2_V_83_fu_674);

assign select_ln76_45_fu_2298_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_338_fu_1598_p4 : p2_V_82_fu_670);

assign select_ln76_46_fu_2306_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_337_fu_1588_p4 : p2_V_81_fu_666);

assign select_ln76_47_fu_2314_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_336_fu_1578_p4 : p2_V_80_fu_662);

assign select_ln76_48_fu_2322_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_335_fu_1568_p4 : p2_V_79_fu_658);

assign select_ln76_49_fu_2330_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_334_fu_1558_p4 : p2_V_78_fu_654);

assign select_ln76_4_fu_1970_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_379_fu_1918_p4 : p2_V_123_fu_834);

assign select_ln76_50_fu_2338_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_333_fu_1548_p4 : p2_V_77_fu_650);

assign select_ln76_51_fu_2346_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_332_fu_1538_p4 : p2_V_76_fu_646);

assign select_ln76_52_fu_2354_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_331_fu_1528_p4 : p2_V_75_fu_642);

assign select_ln76_53_fu_2362_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_330_fu_1518_p4 : p2_V_74_fu_638);

assign select_ln76_54_fu_2370_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_329_fu_1508_p4 : p2_V_73_fu_634);

assign select_ln76_55_fu_2378_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_328_fu_1498_p4 : p2_V_72_fu_630);

assign select_ln76_56_fu_2386_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_327_fu_1488_p4 : p2_V_71_fu_626);

assign select_ln76_57_fu_2394_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_326_fu_1478_p4 : p2_V_70_fu_622);

assign select_ln76_58_fu_2402_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_325_fu_1468_p4 : p2_V_69_fu_618);

assign select_ln76_59_fu_2410_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_324_fu_1458_p4 : p2_V_68_fu_614);

assign select_ln76_5_fu_1978_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_378_fu_1908_p4 : p2_V_122_fu_830);

assign select_ln76_60_fu_2418_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_323_fu_1448_p4 : p2_V_67_fu_610);

assign select_ln76_61_fu_2426_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_322_fu_1438_p4 : p2_V_66_fu_606);

assign select_ln76_62_fu_2434_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_321_fu_1428_p4 : p2_V_65_fu_602);

assign select_ln76_63_fu_2442_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_320_fu_1304_p1 : p2_V_64_fu_598);

assign select_ln76_64_fu_2450_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_63_fu_594 : p2_V_383_fu_1418_p4);

assign select_ln76_65_fu_2458_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_fu_590 : p2_V_382_fu_1408_p4);

assign select_ln76_66_fu_2466_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_1_fu_586 : p2_V_381_fu_1398_p4);

assign select_ln76_67_fu_2474_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_2_fu_582 : p2_V_380_fu_1928_p4);

assign select_ln76_68_fu_2482_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_3_fu_578 : p2_V_379_fu_1918_p4);

assign select_ln76_69_fu_2490_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_4_fu_574 : p2_V_378_fu_1908_p4);

assign select_ln76_6_fu_1986_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_377_fu_1898_p4 : p2_V_121_fu_826);

assign select_ln76_70_fu_2498_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_5_fu_570 : p2_V_377_fu_1898_p4);

assign select_ln76_71_fu_2506_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_6_fu_566 : p2_V_376_fu_1888_p4);

assign select_ln76_72_fu_2514_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_7_fu_562 : p2_V_375_fu_1878_p4);

assign select_ln76_73_fu_2522_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_8_fu_558 : p2_V_374_fu_1868_p4);

assign select_ln76_74_fu_2530_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_9_fu_554 : p2_V_373_fu_1858_p4);

assign select_ln76_75_fu_2538_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_10_fu_550 : p2_V_372_fu_1388_p4);

assign select_ln76_76_fu_2546_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_11_fu_546 : p2_V_371_fu_1378_p4);

assign select_ln76_77_fu_2554_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_12_fu_542 : p2_V_370_fu_1368_p4);

assign select_ln76_78_fu_2562_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_13_fu_538 : p2_V_369_fu_1358_p4);

assign select_ln76_79_fu_2570_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_14_fu_534 : p2_V_368_fu_1348_p4);

assign select_ln76_7_fu_1994_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_376_fu_1888_p4 : p2_V_120_fu_822);

assign select_ln76_80_fu_2578_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_15_fu_530 : p2_V_367_fu_1338_p4);

assign select_ln76_81_fu_2586_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_16_fu_526 : p2_V_366_fu_1328_p4);

assign select_ln76_82_fu_2594_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_17_fu_522 : p2_V_365_fu_1318_p4);

assign select_ln76_83_fu_2602_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_18_fu_518 : p2_V_364_fu_1848_p4);

assign select_ln76_84_fu_2610_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_19_fu_514 : p2_V_363_fu_1838_p4);

assign select_ln76_85_fu_2618_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_20_fu_510 : p2_V_362_fu_1828_p4);

assign select_ln76_86_fu_2626_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_21_fu_506 : p2_V_361_fu_1818_p4);

assign select_ln76_87_fu_2634_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_22_fu_502 : p2_V_360_fu_1808_p4);

assign select_ln76_88_fu_2642_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_23_fu_498 : p2_V_359_fu_1798_p4);

assign select_ln76_89_fu_2650_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_24_fu_494 : p2_V_358_fu_1788_p4);

assign select_ln76_8_fu_2002_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_375_fu_1878_p4 : p2_V_119_fu_818);

assign select_ln76_90_fu_2658_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_25_fu_490 : p2_V_357_fu_1778_p4);

assign select_ln76_91_fu_2666_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_26_fu_486 : p2_V_356_fu_1768_p4);

assign select_ln76_92_fu_2674_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_27_fu_482 : p2_V_355_fu_1758_p4);

assign select_ln76_93_fu_2682_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_28_fu_478 : p2_V_354_fu_1748_p4);

assign select_ln76_94_fu_2690_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_29_fu_474 : p2_V_353_fu_1738_p4);

assign select_ln76_95_fu_2698_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_30_fu_470 : p2_V_352_fu_1728_p4);

assign select_ln76_96_fu_2706_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_31_fu_466 : p2_V_351_fu_1718_p4);

assign select_ln76_97_fu_2714_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_32_fu_462 : p2_V_350_fu_1308_p4);

assign select_ln76_98_fu_2722_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_33_fu_458 : p2_V_349_fu_1708_p4);

assign select_ln76_99_fu_2730_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_34_fu_454 : p2_V_348_fu_1698_p4);

assign select_ln76_9_fu_2010_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_374_fu_1868_p4 : p2_V_118_fu_814);

assign select_ln76_fu_1938_p3 = ((tmp_11_fu_906_p3[0:0] == 1'b1) ? p2_V_383_fu_1418_p4 : p2_V_127_fu_850);

assign shl_ln80_1_fu_4396_p2 = 4'd1 << zext_ln80_7_fu_4392_p1;

assign shl_ln_fu_4073_p3 = {{trunc_ln80_2_fu_4069_p1}, {3'd0}};

assign t_4_fu_896_p2 = (ap_sig_allocacmp_t_3 + 17'd1);

assign tmp_11_fu_906_p3 = ap_sig_allocacmp_t_3[32'd6];

assign tmp_7_fu_3997_p3 = {{c_reg_5388}, {5'd0}};

assign tmp_8_fu_4008_p3 = {{c_reg_5388}, {3'd0}};

assign trunc_ln80_1_fu_4051_p1 = add_ln80_1_fu_4033_p2[13:0];

assign trunc_ln80_2_fu_4069_p1 = w_fu_334[1:0];

assign trunc_ln80_fu_4039_p1 = add_ln80_1_fu_4033_p2[11:0];

assign w_3_fu_4408_p2 = (w_fu_334 + 32'd1);

assign w_4_fu_4426_p3 = ((icmp_ln82_1_fu_4414_p2[0:0] == 1'b1) ? 32'd0 : w_3_fu_4408_p2);

assign w_5_fu_4442_p3 = ((icmp_ln82_fu_4403_p2[0:0] == 1'b1) ? w_4_fu_4426_p3 : w_fu_334);

assign y2_buf_address0 = zext_ln80_4_fu_4097_p1;

assign y2_buf_d0 = zext_ln80_6_fu_4381_p1 << zext_ln80_5_fu_4377_p1;

assign zext_ln80_1_fu_4015_p1 = tmp_8_fu_4008_p3;

assign zext_ln80_2_fu_4025_p1 = add_ln80_fu_4019_p2;

assign zext_ln80_3_fu_4029_p1 = h_fu_338;

assign zext_ln80_4_fu_4097_p1 = add_ln80_3_fu_4091_p2;

assign zext_ln80_5_fu_4377_p1 = shl_ln_fu_4073_p3;

assign zext_ln80_6_fu_4381_p1 = tmp_1_fu_4368_p4;

assign zext_ln80_7_fu_4392_p1 = trunc_ln80_2_fu_4069_p1;

assign zext_ln80_fu_4004_p1 = tmp_7_fu_3997_p3;

endmodule //concat_channel_stream_buffer2
