-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bn_silu_stream is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_s_TDATA : IN STD_LOGIC_VECTOR (2047 downto 0);
    in_s_TVALID : IN STD_LOGIC;
    in_s_TREADY : OUT STD_LOGIC;
    out_s_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    out_s_TVALID : OUT STD_LOGIC;
    out_s_TREADY : IN STD_LOGIC;
    bn_scale_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bn_scale_EN_A : OUT STD_LOGIC;
    bn_scale_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    bn_scale_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bn_scale_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    bn_scale_Clk_A : OUT STD_LOGIC;
    bn_scale_Rst_A : OUT STD_LOGIC;
    bn_shift_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bn_shift_EN_A : OUT STD_LOGIC;
    bn_shift_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    bn_shift_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bn_shift_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    bn_shift_Clk_A : OUT STD_LOGIC;
    bn_shift_Rst_A : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of bn_silu_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bn_silu_stream_bn_silu_stream,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.057000,HLS_SYN_LAT=102462,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=7862,HLS_SYN_LUT=8807,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal input_scale : STD_LOGIC_VECTOR (31 downto 0);
    signal weight_scale : STD_LOGIC_VECTOR (31 downto 0);
    signal output_scale : STD_LOGIC_VECTOR (31 downto 0);
    signal output_scale_read_reg_97 : STD_LOGIC_VECTOR (31 downto 0);
    signal weight_scale_read_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_scale_read_reg_107 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_w_scale_reg_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_92_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inv_out_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_done : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_idle : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_ready : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TREADY : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_EN_A : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_EN_A : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_in_s_TREADY : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TVALID : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_ce : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_ce : STD_LOGIC;
    signal grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_88_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_88_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_92_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_92_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_88_ce : STD_LOGIC;
    signal grp_fu_92_ce : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal regslice_both_out_s_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal regslice_both_in_s_U_apdone_blk : STD_LOGIC;
    signal in_s_TDATA_int_regslice : STD_LOGIC_VECTOR (2047 downto 0);
    signal in_s_TVALID_int_regslice : STD_LOGIC;
    signal in_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_s_U_ack_in : STD_LOGIC;
    signal out_s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_s_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bn_silu_stream_bn_silu_stream_Pipeline_MAIN IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_s_TVALID : IN STD_LOGIC;
        out_s_TREADY : IN STD_LOGIC;
        in_w_scale : IN STD_LOGIC_VECTOR (31 downto 0);
        bn_scale_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        bn_scale_EN_A : OUT STD_LOGIC;
        bn_scale_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        bn_scale_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        bn_scale_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        bn_shift_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        bn_shift_EN_A : OUT STD_LOGIC;
        bn_shift_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        bn_shift_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        bn_shift_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        inv_out : IN STD_LOGIC_VECTOR (31 downto 0);
        in_s_TDATA : IN STD_LOGIC_VECTOR (2047 downto 0);
        in_s_TREADY : OUT STD_LOGIC;
        out_s_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        out_s_TVALID : OUT STD_LOGIC;
        grp_fu_88_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_88_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_88_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_88_p_ce : OUT STD_LOGIC;
        grp_fu_92_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_92_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_92_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_92_p_ce : OUT STD_LOGIC );
    end component;


    component bn_silu_stream_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bn_silu_stream_fdiv_32ns_32ns_32_9_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bn_silu_stream_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        input_scale : OUT STD_LOGIC_VECTOR (31 downto 0);
        weight_scale : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_scale : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component bn_silu_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_bn_silu_stream_Pipeline_MAIN_fu_74 : component bn_silu_stream_bn_silu_stream_Pipeline_MAIN
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start,
        ap_done => grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_done,
        ap_idle => grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_idle,
        ap_ready => grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_ready,
        in_s_TVALID => in_s_TVALID_int_regslice,
        out_s_TREADY => grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TREADY,
        in_w_scale => in_w_scale_reg_112,
        bn_scale_Addr_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_Addr_A,
        bn_scale_EN_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_EN_A,
        bn_scale_WEN_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_WEN_A,
        bn_scale_Din_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_Din_A,
        bn_scale_Dout_A => bn_scale_Dout_A,
        bn_shift_Addr_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_Addr_A,
        bn_shift_EN_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_EN_A,
        bn_shift_WEN_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_WEN_A,
        bn_shift_Din_A => grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_Din_A,
        bn_shift_Dout_A => bn_shift_Dout_A,
        inv_out => inv_out_reg_117,
        in_s_TDATA => in_s_TDATA_int_regslice,
        in_s_TREADY => grp_bn_silu_stream_Pipeline_MAIN_fu_74_in_s_TREADY,
        out_s_TDATA => grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TDATA,
        out_s_TVALID => grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TVALID,
        grp_fu_88_p_din0 => grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din0,
        grp_fu_88_p_din1 => grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din1,
        grp_fu_88_p_dout0 => grp_fu_88_p2,
        grp_fu_88_p_ce => grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_ce,
        grp_fu_92_p_din0 => grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din0,
        grp_fu_92_p_din1 => grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din1,
        grp_fu_92_p_dout0 => grp_fu_92_p2,
        grp_fu_92_p_ce => grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_ce);

    control_s_axi_U : component bn_silu_stream_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        input_scale => input_scale,
        weight_scale => weight_scale,
        output_scale => output_scale,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    fmul_32ns_32ns_32_3_max_dsp_1_U91 : component bn_silu_stream_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_88_p0,
        din1 => grp_fu_88_p1,
        ce => grp_fu_88_ce,
        dout => grp_fu_88_p2);

    fdiv_32ns_32ns_32_9_no_dsp_1_U92 : component bn_silu_stream_fdiv_32ns_32ns_32_9_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_92_p0,
        din1 => grp_fu_92_p1,
        ce => grp_fu_92_ce,
        dout => grp_fu_92_p2);

    regslice_both_in_s_U : component bn_silu_stream_regslice_both
    generic map (
        DataWidth => 2048)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_s_TDATA,
        vld_in => in_s_TVALID,
        ack_in => regslice_both_in_s_U_ack_in,
        data_out => in_s_TDATA_int_regslice,
        vld_out => in_s_TVALID_int_regslice,
        ack_out => in_s_TREADY_int_regslice,
        apdone_blk => regslice_both_in_s_U_apdone_blk);

    regslice_both_out_s_U : component bn_silu_stream_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TDATA,
        vld_in => grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TVALID,
        ack_in => out_s_TREADY_int_regslice,
        data_out => out_s_TDATA,
        vld_out => regslice_both_out_s_U_vld_out,
        ack_out => out_s_TREADY,
        apdone_blk => regslice_both_out_s_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                in_w_scale_reg_112 <= grp_fu_88_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                input_scale_read_reg_107 <= input_scale;
                output_scale_read_reg_97 <= output_scale;
                weight_scale_read_reg_102 <= weight_scale;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                inv_out_reg_117 <= grp_fu_92_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_done, ap_CS_fsm_state12, ap_CS_fsm_state13, regslice_both_out_s_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (regslice_both_out_s_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_done)
    begin
        if ((grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state13_blk_assign_proc : process(regslice_both_out_s_U_apdone_blk)
    begin
        if ((regslice_both_out_s_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state13, regslice_both_out_s_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (regslice_both_out_s_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13, regslice_both_out_s_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (regslice_both_out_s_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bn_scale_Addr_A <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_Addr_A;
    bn_scale_Clk_A <= ap_clk;
    bn_scale_Din_A <= ap_const_lv32_0;
    bn_scale_EN_A <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_scale_EN_A;
    bn_scale_Rst_A <= ap_rst_n_inv;
    bn_scale_WEN_A <= ap_const_lv4_0;
    bn_shift_Addr_A <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_Addr_A;
    bn_shift_Clk_A <= ap_clk;
    bn_shift_Din_A <= ap_const_lv32_0;
    bn_shift_EN_A <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_bn_shift_EN_A;
    bn_shift_Rst_A <= ap_rst_n_inv;
    bn_shift_WEN_A <= ap_const_lv4_0;
    grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_ap_start_reg;
    grp_bn_silu_stream_Pipeline_MAIN_fu_74_out_s_TREADY <= (out_s_TREADY_int_regslice and ap_CS_fsm_state12);

    grp_fu_88_ce_assign_proc : process(grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_88_ce <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_ce;
        else 
            grp_fu_88_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_88_p0_assign_proc : process(input_scale_read_reg_107, grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din0, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_88_p0 <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_88_p0 <= input_scale_read_reg_107;
        else 
            grp_fu_88_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_88_p1_assign_proc : process(weight_scale_read_reg_102, grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din1, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_88_p1 <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_88_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_88_p1 <= weight_scale_read_reg_102;
        else 
            grp_fu_88_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_92_ce_assign_proc : process(grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_92_ce <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_ce;
        else 
            grp_fu_92_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_92_p0_assign_proc : process(grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din0, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_92_p0 <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_92_p0 <= ap_const_lv32_3F800000;
        else 
            grp_fu_92_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_92_p1_assign_proc : process(output_scale_read_reg_97, grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din1, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_92_p1 <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_grp_fu_92_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_92_p1 <= output_scale_read_reg_97;
        else 
            grp_fu_92_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    in_s_TREADY <= regslice_both_in_s_U_ack_in;

    in_s_TREADY_int_regslice_assign_proc : process(grp_bn_silu_stream_Pipeline_MAIN_fu_74_in_s_TREADY, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            in_s_TREADY_int_regslice <= grp_bn_silu_stream_Pipeline_MAIN_fu_74_in_s_TREADY;
        else 
            in_s_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    out_s_TVALID <= regslice_both_out_s_U_vld_out;
end behav;
