-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity concat_channel_stream_combine is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    y3_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    y3_s_TVALID : IN STD_LOGIC;
    y3_s_TREADY : OUT STD_LOGIC;
    y0_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    y0_buf_ce0 : OUT STD_LOGIC;
    y0_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    y1_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    y1_buf_ce0 : OUT STD_LOGIC;
    y1_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    y2_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    y2_buf_ce0 : OUT STD_LOGIC;
    y2_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    scale0 : IN STD_LOGIC_VECTOR (31 downto 0);
    scale1 : IN STD_LOGIC_VECTOR (31 downto 0);
    scale2 : IN STD_LOGIC_VECTOR (31 downto 0);
    scale3 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_scale : IN STD_LOGIC_VECTOR (31 downto 0);
    out_s_TDATA : OUT STD_LOGIC_VECTOR (2047 downto 0);
    out_s_TVALID : OUT STD_LOGIC;
    out_s_TREADY : IN STD_LOGIC );
end;


architecture behav of concat_channel_stream_combine is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_91_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inv_out_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_idle : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_ready : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TREADY : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_ce0 : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_ce0 : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_ce0 : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TDATA : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TVALID : STD_LOGIC;
    signal grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm_state10 : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component concat_channel_stream_combine_Pipeline_COMBINE_MAIN IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y3_s_TVALID : IN STD_LOGIC;
        out_s_TREADY : IN STD_LOGIC;
        y0_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y0_buf_ce0 : OUT STD_LOGIC;
        y0_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        y1_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y1_buf_ce0 : OUT STD_LOGIC;
        y1_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        y2_buf_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        y2_buf_ce0 : OUT STD_LOGIC;
        y2_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale0 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale3 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale1 : IN STD_LOGIC_VECTOR (31 downto 0);
        scale2 : IN STD_LOGIC_VECTOR (31 downto 0);
        inv_out : IN STD_LOGIC_VECTOR (31 downto 0);
        y3_s_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        y3_s_TREADY : OUT STD_LOGIC;
        out_s_TDATA : OUT STD_LOGIC_VECTOR (2047 downto 0);
        out_s_TVALID : OUT STD_LOGIC );
    end component;


    component concat_channel_stream_fdiv_32ns_32ns_32_9_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_combine_Pipeline_COMBINE_MAIN_fu_72 : component concat_channel_stream_combine_Pipeline_COMBINE_MAIN
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start,
        ap_done => grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done,
        ap_idle => grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_idle,
        ap_ready => grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_ready,
        y3_s_TVALID => y3_s_TVALID,
        out_s_TREADY => grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TREADY,
        y0_buf_address0 => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_address0,
        y0_buf_ce0 => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_ce0,
        y0_buf_q0 => y0_buf_q0,
        y1_buf_address0 => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_address0,
        y1_buf_ce0 => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_ce0,
        y1_buf_q0 => y1_buf_q0,
        y2_buf_address0 => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_address0,
        y2_buf_ce0 => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_ce0,
        y2_buf_q0 => y2_buf_q0,
        scale0 => scale0,
        scale3 => scale3,
        scale1 => scale1,
        scale2 => scale2,
        inv_out => inv_out_reg_122,
        y3_s_TDATA => y3_s_TDATA,
        y3_s_TREADY => grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY,
        out_s_TDATA => grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TDATA,
        out_s_TVALID => grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TVALID);

    fdiv_32ns_32ns_32_9_no_dsp_1_U296 : component concat_channel_stream_fdiv_32ns_32ns_32_9_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_3F800000,
        din1 => output_scale,
        ce => ap_const_logic_1,
        dout => grp_fu_91_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_logic_1 = ap_NS_fsm_state10))) then 
                    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_ready = ap_const_logic_1)) then 
                    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                inv_out_reg_122 <= grp_fu_91_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done, ap_CS_fsm_state11)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_NS_fsm_state10 <= ap_NS_fsm(9);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done)
    begin
        if ((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done, ap_CS_fsm_state11)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done, ap_CS_fsm_state11)
    begin
        if (((grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_ap_start_reg;
    grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TREADY <= (out_s_TREADY and ap_CS_fsm_state11);
    out_s_TDATA <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TDATA;
    out_s_TVALID <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_out_s_TVALID;
    y0_buf_address0 <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_address0;
    y0_buf_ce0 <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y0_buf_ce0;
    y1_buf_address0 <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_address0;
    y1_buf_ce0 <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y1_buf_ce0;
    y2_buf_address0 <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_address0;
    y2_buf_ce0 <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y2_buf_ce0;

    y3_s_TREADY_assign_proc : process(grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            y3_s_TREADY <= grp_combine_Pipeline_COMBINE_MAIN_fu_72_y3_s_TREADY;
        else 
            y3_s_TREADY <= ap_const_logic_0;
        end if; 
    end process;

end behav;
